### ISSUE TITLE
Add .ptr_type to AnyType trait

### ISSUE THREAD

**Issue by jyn514** [TheDan64/inkwell#100]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I want to create a pointer to a type and I have to match every member of the enum individually.

**Describe the solution you'd like**
Every variant of `AnyTypeEnum` has a `ptr_type` function. `ptr_type` should be part of the `AnyType` trait so I don't have to pattern match every time. This is similar to how `fn_type` is provided for all implementors of `BasicType`.

**Describe possible drawbacks to your solution**
No drawbacks I can think of.

**Describe alternatives you've considered**
Pattern match on every member of the enum and call `matched.ptr_type()` explicitly.

**Comment by jyn514** [comment]
Here's the code for doing this without the trait:

```
macro_rules! gen_ptrs {
    ( $_self: ident, $addr: expr, $( $id: ident ),* ) => {
        match $_self {
            $( $id(t) => t.ptr_type($addr), )*
        }
    }
}

trait ToPointerType {
    fn ptr_type(&self, address_space: AddressSpace) -> types::PointerType;
}

impl ToPointerType for AnyTypeEnum {
    fn ptr_type(&self, addr: AddressSpace) -> types::PointerType {
        use AnyTypeEnum::*;
        gen_ptrs!(
            self,
            addr,
            VoidType,
            PointerType,
            FloatType,
            IntType,
            FunctionType,
            StructType,
            VectorType,
            ArrayType
        )
    }
}
```

**Comment by jyn514** [comment]
Similar request for adding `.array_type` to `BasicType`

**Comment by TheDan64** [comment]
> Every variant of AnyTypeEnum has a ptr_type function. 

As discovered in #96, you shouldn't be able create void pointers. So at best this function would have to be fallible.

> Here's the code for doing this without the trait: `...`

There's no need for this to be its own trait, it should just go on the `AnyType` trait. And a simple match would suffice over a macro since the macro won't be reused anywhere else

**Comment by jyn514** [comment]
> As discovered in #96, you shouldn't be able create void pointers. So at best this function would have to be fallible.

That's fine, `.try_ptr_type` would still be convenient and useful.

> There's no need for this to be its own trait, it should just go on the AnyType trait.
I don't think there's a way to add functions to a trait in a different crate.

> And a simple match would suffice over a macro since the macro won't be reused anywhere else
The macro is because there's a lot of repetitive typing I didn't feel like doing. I also reused it for `array_type` with modifications.

---

I might take a stab at this. https://github.com/TheDan64/inkwell/blob/master/.github/CONTRIBUTING.md#required mentions following the project code style, is this written anywhere or should I just read the existing code for examples?

**Comment by TheDan64** [comment]
The trait is from this crate. And yeah just use existing code. Eventually it will be formalized by rustfmt

**Comment by jyn514** [comment]
Added in https://github.com/TheDan64/inkwell/pull/101
