### ISSUE TITLE
MemoryBuffer.create_object_file returns None

### ISSUE THREAD

**Issue by jyn514** [TheDan64/inkwell#102]
**Describe the Bug**
`MemoryBuffer.create_object_file` returns None for valid inputs.

**To Reproduce**
```rust
$ cat src/main.rs
extern crate inkwell;
use inkwell::memory_buffer::MemoryBuffer;

fn main() {
    let asm_buf = MemoryBuffer::create_from_memory_range(
        "; ModuleID = 'main'
source_filename = \"main\"

define i32 @main() {
main:
  ret i32 0
}
",
        "main",
    );
    let obj_file = asm_buf.create_object_file();
    assert!(obj_file.is_some());
}
$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.02s
     Running `target/debug/inkwell-test`
thread 'main' panicked at 'assertion failed: obj_file.is_some()', src/main.rs:17:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Expected Behavior**
`obj_file` should be `Some(ObjectFile)`.

**LLVM Version (please complete the following information):**
 - LLVM Version: 6.0
 - Inkwell Branch Used: llvm6-0

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.2 LTS

**Additional Context**
`ObjectFile` in general seems to be a bit of a neglected API, I couldn't find a way to write it to disk or get access to the raw memory for instance.

**Comment by jyn514** [comment]
I was incorrect - this is invalid input.

```
$ llc main.ll
llc: main.ll:2:19: error: expected string constant
source_filename = \"main\"
```

This error wasn't at all obvious from the `None` though - the interface should be changed to return a `Result` instead

**Comment by TheDan64** [comment]
I think the return type is an option because LLVM simply returns a null pointer, rather than anything helpful like an error message. So `None` is a natural equivalent. (There's no `ObjectFile` to give)

That said, you do bring up a good point about it being an error - so I wouldn't be against changing it to `Result<ObjectFile, ()>`

**Comment by jyn514** [comment]
There's definitely no way to get an error message? That seems like a really weird API decision from LLVM

**Comment by TheDan64** [comment]
They do have a function to get error messages in newer LLVM versions, so it could potentially work here, though I haven't tested it

**Comment by jyn514** [comment]
Mildly related, I have a process question - how do you debug llvm? I've tried `gdb` but it doesn't step into the ffi functions

**Comment by TheDan64** [comment]
`gdb` and read the LLVM source lol. `Valgrind` if it's really bad

**Comment by jyn514** [comment]
See I think I must be missing the debug symbols or something then because gdb won't step into any of the C++ calls.

```
(gdb) n
16          let obj_file = asm_buf.create_object_file();
(gdb) step
inkwell::memory_buffer::MemoryBuffer::create_object_file (self=...)
    at /home/joshua/.cargo/git/checkouts/inkwell-946411d814d2c9f8/28ce791/src/memory_buffer.rs:120
120             let object_file = unsafe {
(gdb) step
121                 LLVMCreateObjectFile(self.memory_buffer)
(gdb) step
121                 LLVMCreateObjectFile(self.memory_buffer)
(gdb) step
124             forget(self);
```

**Comment by TheDan64** [comment]
If you (or anyone else reading this) is interested in tackling this, you should see if this function will get you an error message:
https://github.com/TheDan64/inkwell/blob/a34b58ce44c32ef4d5b62b5d07aced61711fc514/src/support/error_handling.rs#L63-L78

IE it's used here for example:
https://github.com/TheDan64/inkwell/blob/a34b58ce44c32ef4d5b62b5d07aced61711fc514/src/module.rs#L1310-L1321

**Comment by TheDan64** [comment]
I can't seem to extract an error message since there's no context (and trying with the global context doesn't work...) so I'll just return `Err(())` instead, to make it more clear that an error occurred.

**Comment by TheDan64** [comment]
Yep, in the definition for `LLVMCreateObjectFile` is this wonderful comment: `// TODO: Actually report errors helpfully.`
