### ISSUE TITLE
alignment on load and store instructions

### ISSUE THREAD

**Issue by nlewycky** [TheDan64/inkwell#110]
**Is your feature request related to a problem? Please describe.**
LLVMGetAlignment and LLVMSetAlignment apply to GlobalValue, AllocaInst, LoadInst and StoreInst (exhaustive list). Inkwell only provides it for GlobalValue.

**Describe the solution you'd like**
Some way to set the alignment when it's valid to do so.

I think it would make sense to have a trait that encapsulates LoadInst and another trait that encapsulates StoreInst, and that this can only be casted-to when LLVMIsALoad() or LLVMIsAStore() are true respectively. It'd be great if builder.build_load/store could return a trait, but from my limited understanding of Rust that can't happen because traits are unsized types?

**Comment by TheDan64** [comment]
Not sure if traits are the best approach here, but you could return one dynamically or statically and existentially

**Comment by TheDan64** [comment]
ie, `Box<dyn Trait>` or `impl Trait`, respectively
