### ISSUE TITLE
atomic ordering for load and store

### ISSUE THREAD

**Issue by nlewycky** [TheDan64/inkwell#111]
**Is your feature request related to a problem? Please describe.**
I'd like atomic loads and stores in my LLVM IR.

**Describe the solution you'd like**
The LLVM API does not have distinct atomic and non-atomic loads and stores, the atomic order is a mutable property of a load or store. We could follow that pattern and allow calls to LLVMSetOrdering and LLVMGetOrdering, which are valid if-and-only-if the Value in question is a LoadInst or a StoreInst.

**Describe possible drawbacks to your solution**
I spend the rest of my life debugging data races.

**Describe alternatives you've considered**
We could add `build_atomic_load` and `build_atomic_store` instead. This is perhaps more convenient, and sufficient for my purposes, but it doesn't fully expose the functionality that llvm permits (mutating the atomicity after construction).

But, we could have both build_atomic_store and set/get ordering of storeinst.

**Additional context**
Atomic ordering is mutable is to make life easier for llvm's optimization passes. I don't think people are expected to write optimization passes in inkwell.

**Comment by nlewycky** [comment]
This depends on #110. To quote https://llvm.org/docs/LangRef.html#load-instruction
> `align` must be explicitly specified on atomic loads

and similarly https://llvm.org/docs/LangRef.html#store-instruction

> `align` must be explicitly specified on atomic stores

**Comment by TheDan64** [comment]
The most straightforward thing to do for this and #110 is probably just to add the methods to `InstructionValue`s and check that the instruction type is correct at runtime and return an error if not.

In the future this could possibly be constrained to `InstructionValue` subtypes, ie `InstructionValue<Store>` like we did for pass managers.
