### ISSUE TITLE
Internal macros crate can't be published

### ISSUE THREAD

**Issue by MarkMcCaskey** [TheDan64/inkwell#124]
**Describe the Bug**
The `build.rs` of the `internal_macros` subcrate prevents it from being published.

**To Reproduce**
`cargo publish --dry-run`

**Expected Behavior**
The command should succeed

**LLVM Version (please complete the following information):**
 - LLVM Version: 8.0
 - Inkwell Branch Used: master

**Desktop (please complete the following information):**
 - OS: OSX 10.15

**Additional Context**
Output of the command:
```
error: failed to verify package tarball

Caused by:
  failed to run custom build command for `inkwell_internal_macros v0.1.0 (/private/tmp/inkwell/internal_macros/target/package/inkwell_internal_macros-0.1.0)`

Caused by:
  process didn't exit successfully: `/private/tmp/inkwell/internal_macros/target/package/inkwell_internal_macros-0.1.0/target/debug/build/inkwell_internal_macros-1e41ebd0195fe121/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Unable to load Cargo manifest!: Io(Os { code: 2, kind: NotFound, message: "No such file or directory" })', src/libcore/result.rs:999:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by TheDan64** [comment]
Fixed by dd20ecb80c3d32c0b9b83dbb703365e9eb500efe
