### ISSUE TITLE
Metadata handling is broken

### ISSUE THREAD

**Issue by seanyoung** [TheDan64/inkwell#130]
**Describe the Bug**
cargo test sometimes fails

**To Reproduce**
Run under valgrind:
1. Run cargo test
2. Find the line that looks like "Running target/debug/deps/all-9eb5b5ba7c1d722f"
3. Run `valgrind ./target/debug/deps/all-9eb5b5ba7c1d722f`

Please provide a simple sample of code which reproduces the issue on your machine.

**Expected Behavior**

**LLVM Version (please complete the following information):**
 - LLVM Version: 8.0
 - Inkwell Branch Used: llvm8-0

**Desktop (please complete the following information):**
 - OS: Fedora 31

**Additional Context**
LLVMHasMetadata(), LLVMGetMetadata() and LLVMSetMetadata() all take Instructions as
arguments, see:
https://github.com/llvm/llvm-project/blob/release/8.x/llvm/lib/IR/Core.cpp#L851
So:
https://github.com/TheDan64/inkwell/blob/master/src/values/mod.rs#L172
Is broken.

**Comment by TheDan64** [comment]
Good catch, I think the solution is to just add

```rust
if !self.is_instruction() {
    return false;
}
```

to the top of `has_metadata`. Feel free to PR this change if you wish
