### ISSUE TITLE
inkwell-internals should not make http requests

### ISSUE THREAD

**Issue by Brekcel** [TheDan64/inkwell#137]
**Describe the Bug**
`internal_macros` uses an http request via `reqwest` which it should not do.

**To Reproduce**
Attempt to build `inkwell` using the published `internal_macros:0.1.0` instead of the local path without internet.

**Expected Behavior**
The crate should build (as long as it has already been downloaded).

**LLVM Version:**
 - LLVM Version: 8.0.1
 - Inkwell Branch Used: llvm8-0

**Desktop:**
 Windows 10

**Additional Context**
Currently (change made in dd20ecb) `internal_macros` build script try's to fetch `inkwells` cargo.toml from the parent directory. If that fails then it makes an http request, via `reqwest`, to this github projects cargo.toml. This has 3 issues: 1. When developing locally, `internal_macros` should always have access to a parent directory and never need to make the http request. Always compiling `reqwest` bloats the dependecy count from 64 to 209 and more than doubles compile times. All for a scenario that should never occur. 2. Published versions of `inkwell` cannot build without internet connection. 3. While building the crate, it will always use master's `cargo.toml`. If a change is made to master's `cargo.toml`, then all crates that are built from the published version of `inkwell_internals` will have incorrect values.

**Comment by TheDan64** [comment]
Not sure I agree with all of your points, but I do agree that it's suboptimal. It was introduced as a way to stay DRY and not duplicate LLVM version info between the two crates.

> Attempt to build inkwell using the published internal_macros:0.1.0 instead of the local path without internet.

If you're building locally, you should be using the local `internal_macros` crate, not the published one.

> When developing locally, internal_macros should always have access to a parent directory and never need to make the http request.

Using the local `internal_macros` means it doesn't make an HTTP request (that's how it's currently set up), so I'm not sure I follow your point here.

> Always compiling reqwest bloats the dependecy count from 64 to 209 and more than doubles compile times.

Agreed that it's not ideal.

> Published versions of inkwell cannot build without internet connection.

There are no published versions of inkwell at the moment, so this shouldn't even be a problem at all. But agreed wrt long term.

> While building the crate, it will always use master's cargo.toml. If a change is made to master's cargo.toml, then all crates that are built from the published version of inkwell_internals will have incorrect values.

This is a good point.

Anyway, the publishing of the internals crate was more so a test run and one to reserve the crate name. This should not be an issue for any local development. I'm open to ideas, and do think this should be improved, but I don't currently see a better way to keep LLVM version info DRY.

**Comment by Brekcel** [comment]
> > When developing locally, internal_macros should always have access to a parent directory and never need to make the http request.

> Using the local internal_macros means it doesn't make an HTTP request (that's how it's currently set up), so I'm not sure I follow your point here.

The point I was trying to make here was that since it doesn't make an http request, the dependency is unneeded in this scenario, and so is the dependency bloat.

> I'm open to ideas, and do think this should be improved, but I don't currently see a better way to keep LLVM version info DRY.

I'm not sure of a way to keep it 100% DRY to be honest. All the ways that I can think of so far involve at least a small bit of repeating.

**Comment by sunng87** [comment]
@TheDan64 could you please release a new version of inkwell_internals on crates.io? The 0.1.0 there still has build.rs

**Comment by TheDan64** [comment]
Good catch, sorry about that. I've pushed a 0.2.0. Though I don't think you'll be able to use it with the existing release, except locally.
