### ISSUE TITLE
Types & Values should be Copy + Clone

### ISSUE THREAD

**Issue by TheDan64** [TheDan64/inkwell#14]
Rust does this for [their Value types](https://github.com/rust-lang/rust/blob/1b38776c1f68c6fd47c1b2f7b7974efc7dd64901/src/librustc_trans/value.rs#L16) and LLVM suggests Types [are singletons](https://llvm.org/doxygen/classllvm_1_1Type.html#details). Although Values don't seem to be singletons, this should still be safe to do.

**Comment by 6A** [comment]
I should be able to take care of this by the end of the day, and add tests related to this as well if possible.

**Comment by TheDan64** [comment]
Thanks again for bringing this up! I really appreciate the feedback.

**Comment by TheDan64** [comment]
Reopening in favor of deriving this functionality for macro generated enums and traits.
