### ISSUE TITLE
Add Builder functions for LLVM C library intrinsics

### ISSUE THREAD

**Issue by willtunnels** [TheDan64/inkwell#145]
LLVM offers a number of intrinsics roughly corresponding to C library functions, for instance `memcpy` and `memset`. From the [LLVM reference](https://llvm.org/docs/LangRef.html): "these intrinsics allow source-language front-ends to pass information about the alignment of the pointer arguments to the code generator, providing opportunity for more efficient code generation."

It would be nice if inkwell provided access to these intrinsics.

The implementation would probably consist of a few trivial wrappers in the `Builder` for llvm-sys functions.

**Comment by TheDan64** [comment]
This is already implemented in the changes mentioned in #143 I believe

**Comment by TheDan64** [comment]
CC #147

**Comment by rtfeldman** [comment]
> This is already implemented in the changes mentioned in #143 I believe

I looked at the branch and it looks like they aren't.

If you're open to it, I'd be happy to make a separate PR into `master` to introduce `build_memcpy` - it'd be a wrapper around [`LLVMBuildMemCpy`](https://thedan64.github.io/inkwell/llvm_sys/core/fn.LLVMBuildMemSet.html) very similar to how [`build_malloc`](https://thedan64.github.io/inkwell/inkwell/builder/struct.Builder.html#method.build_malloc) wraps [`LLVMBuildMalloc`](https://thedan64.github.io/inkwell/llvm_sys/core/fn.LLVMBuildMalloc.html).

**Comment by TheDan64** [comment]
Sure, go for it!

**Comment by duci9y** [comment]
While I don't feel confident making a PR myself (yet), would love to see a `build_memset` as well.
