### ISSUE TITLE
Long compilation times

### ISSUE THREAD

**Issue by PaperPlaneSoftware** [TheDan64/inkwell#146]
Not sure if this is a bug or not but I'm experiencing long compilation times (> 2 mins) when using Inkwell. 2 mins doesn't sound like much but it feels like an eternity when developing.

I'm on Windows 10, using a manually compiled Release version of LLVM 8.0.1 compiled using Visual Studio 2019.

**Comment by TheDan64** [comment]
You should develop with debug builds, not release

**Comment by PaperPlaneSoftware** [comment]
Hmm, I wonder what's happening. I'm using the latest stable Rust (1.40.0) maybe trying an earlier version will help. I'll give it a go.

**Comment by TheDan64** [comment]
Newer rust will probably be faster, so not sure

**Comment by TheDan64** [comment]
I was able to compile inkwell in release mode, from scratch, in 37s. Rust v1.40. So it might just boil down to your machine? ~30s doesn't seem unreasonable to me

**Comment by TheDan64** [comment]
I'm going to close this as there's nothing actionable here.
