### ISSUE TITLE
Module::set_target doesn't correctly set the target!

### ISSUE THREAD

**Issue by willtunnels** [TheDan64/inkwell#149]
`LLVMSetTarget` (which is called by `Module::set_target`) takes, as its argument, a target triple. This is *not* the same thing as the result of a call to inkwell's `Target::get_name`, which is the value inkwell currently passes `Module::set_target`.

If I create a `Target` with triple "x86_64-pc-linux-gnu" and then call `Module::set_target`, the resulting .ll file will be annotated with `target triple = "x86-64"` and `llc` will not be able to compile it. The correct annotation would be "x86_64-pc-linux-gnu".

**Comment by TheDan64** [comment]
Good catch, we probably want `TargetMachine::get_triple()`?

**Comment by TheDan64** [comment]
Or maybe even just a string since LLVM doesn't seem to care what string you give it?

**Comment by willtunnels** [comment]
I think we want `TargetMachine::get_triple()` like you mentioned. My understanding is that it matters what you give LLVM in so far as giving it the correct triple can help it optimize your IR (I read this in one of the LLVM references though I can't remember exactly where off the top of my head).

The only reason I didn't submit a pull request for this is that I do not know how to fix this without a breaking change (since it seems like we need a `TargetMachine` rather than a `Target`). Though arguably code that calls this function is already broken since attempting to compile to generated IR will, as a rule, fail.

**Comment by TheDan64** [comment]
Sure, I just meant that it seems to be memory safe to provide it an invalid string as far as I can tell. In any case, feel free to PR with the `TargetMachine` change. A breaking change is fine here for correctness (also we're pre-1.0)

**Comment by willtunnels** [comment]
I've been looking at this and there actually is a somewhat meaningful choice to be made. In particular, what should happen with `Module::get_target`. Right now it returns a `Target`. You could argue that now it should return a `TargetMachine` but `Module::set_target` is lossy in that you're really only storing the target triple and only the target triple will be returned from `LLVMGetTarget`, which is not enough to reconstruct the `TargetMachine`. Now, you could store a ref to the machine. But I think this issue actually points to a moderately deeper problem. Somethings take an "entire" machine and somethings just take a triple and these two things are not the same (though a machine does include a triple).

This leads to solution two: just pass strings in and out of set/get target. However, I think a much better solution is to reify the notion of a triple by adding a new struct, `inkwell::targets::TargetTriple`, and adjusting functions across the API to deal in such objects.
