### ISSUE TITLE
build_malloc segfaults with certain arguments

### ISSUE THREAD

**Issue by willtunnels** [TheDan64/inkwell#150]
If you call `Builder::build_malloc` with an argument for which `is_sized()` returns `false`, it will segfault. A simple solution to this is to check `is_sized()` before shelling out to `llvm-sys` and panic if it is `false`. I can submit a PR for this.

One interesting thing about `build_malloc` is that neither clang, swiftc, nor rustc call it (or their LLVM API's equivalent), preferring to build a call to libc malloc instead -- at least this is my understanding after digging through their repositories a bit. Also, based on the code `build_malloc` generates and based on the fact that a malloc intrinsic is not mentioned in the LLVM 10 reference, my impression is that it might just be little more than a convenience function provided by the LLVM API. Perhaps it would be good to give it a `deprecated` annotation or otherwise discourage its use?

**Comment by TheDan64** [comment]
Rust lets you create a `Box<()>` which allocates no space, and I think, sets the pointer equal to 1 in that case because `()` is unsized. I'd guess they avoid calling malloc for that reason.

I think
1) We should see if the malloc code/docs indicate it should never be called on an unsized type
2) Return a result rather than panic

**Comment by willtunnels** [comment]
1. I couldn't find any docs but `LLVMBuildMalloc` makes an internal call to `SizeOf`, which is where it panics. This means that the segfault is in line with what we should expect as it's fundamentally the same issue that forces us to check `is_sized` in `ArrayType::size_of` etc.
2. Returning a `Result` is a good idea.
