### ISSUE TITLE
Improved support for metadata

### ISSUE THREAD

**Issue by MarkMcCaskey** [TheDan64/inkwell#153]
**Is your feature request related to a problem? Please describe.**
When attempting to add support for value-tracking in Wasmer's llvm-backend with some of the [debug intrinsics](https://llvm.org/docs/SourceLevelDebugging.html#llvm-dbg-addr) I ran into a few issues with some of the APIs in Inkwell.

**Describe the solution you'd like**
- [ ] The metadata type should be accessible from `Context` through something like `Context::metadata_type`, similar to other types.
- [ ] Methods like [`VoidType::fn_type`](https://thedan64.github.io/inkwell/inkwell/types/struct.VoidType.html#method.fn_type) should take values that can include the metadata type, perhaps [BasicMetadataValueEnum](https://thedan64.github.io/inkwell/inkwell/values/enum.BasicMetadataValueEnum.html) works here?  This is required for functions like [`llvm.dbg.addr`](https://llvm.org/docs/SourceLevelDebugging.html#llvm-dbg-addr)
- [ ] Support for [Specialized Metadata nodes](https://llvm.org/docs/LangRef.html#specialized-metadata-nodes) (this may make more sense as a separate issue)

**Describe possible drawbacks to your solution**
More code = more complexity, but it brings it closer to what LLVM can do.

**Describe alternatives you've considered**
None applicable that I can think of

**Additional context**
It looks like there are some panics in the code base that indicate that this is a known issue, but I didn't see an issue filed on it!

**Comment by TheDan64** [comment]
>  The metadata type should be accessible from Context through something like Context::metadata_type, similar to other types.

Does the LLVM C API have Context centric functions for creating metadata types? And does it let you turn those types into values? If so, then sure.

> Methods like VoidType::fn_type should take values that can include the metadata type, perhaps BasicMetadataValueEnum works here? This is required for functions like llvm.dbg.addr

It might be simpler to do what the LLVM9 PR does here https://github.com/TheDan64/inkwell/pull/147/files#diff-cc1cadebb5770328d1404803e7a56327R219 to get an intrinsic? But yes, your suggestion is a possibility.

>  Support for Specialized Metadata nodes (this may make more sense as a separate issue)

If the C API supports it, then sure. The LLVM docs said almost nothing useful. lol
