### ISSUE TITLE
Safe Struct GEP

### ISSUE THREAD

**Issue by willtunnels** [TheDan64/inkwell#156]
**Is your feature request related to a problem? Please describe.**
In my personal experience, it is very easy to index incorrectly into a struct when using `Builder::build_struct_gep`, which results in a segfault. It would be nice to make `Builder::build_struct_gep` safe.

**Describe the solution you'd like**
1. Convert the `PointerValue` argument to `Builder::build_struct_gep` into a `StructValue`
2. Get the type of that `StructValue`
3. Call `StructType::count_fields` before performing the actual GEP.

**Describe possible drawbacks to your solution**
I can't think of any drawback.

**Describe alternatives you've considered**
This seems like the only obvious design.

**Comment by TheDan64** [comment]
You'd need to validate that the `PointerValue` is pointing to a struct, but yes, this might be possible.
