### ISSUE TITLE
use lists for basic blocks

### ISSUE THREAD

**Issue by nlewycky** [TheDan64/inkwell#161]
**Is your feature request related to a problem? Please describe.**
Currently, BasicValueUse is restricted to basic values and instruction values. Inkwell doesn't ordinarily treat BasicBlocks as Values, following the precedent of the LLVM C API, even though they totally are Values and they have use lists.

**Describe the solution you'd like**
Expand the use-list functionality to work on BasicBlocks too.

BasicBlocks are "strange Values", they're Values in the LLVM C++ internals, but they have special unusual properties (they're the only Value which is also a container, they aren't a User) and are rarely treated generically as Values. The LLVM C API makes them a separate type which makes sense to impl

**Describe possible drawbacks to your solution**
I don't think adding this hinders any other component.

**Describe alternatives you've considered**
The actual functionality I need is simply to know whether the block has any users or not (akin to `V->use_empty()` in C++, which is roughly `LLVMGetFirstUse(V) == NULL` through the C API).

As an aside, when the use-list is empty (and the Value has a parent), `delete` becomes a safe operation. Also, after a call to `replace_all_uses_with`, the use-list is guaranteed to be empty. It may make sense to create merged operations "delete-if-empty -> bool did-delete" and "delete-in-favour-of -> ()" operations that perform safe deletion.

**Additional context**
The use list of a basic block contains the terminator instructions of the predecessors, the phi nodes of some of the successors (but not necessarily all successors have any phi nodes), and any BlockAddress constants that use this block.

**Comment by TheDan64** [comment]
> As an aside, when the use-list is empty (and the Value has a parent), delete becomes a safe operation.

I'm not sure that this is correct. As `BasicBlock` is `Copy`, you could easily have a duplicate block hanging around after you delete the original and then manipulation of the copy will do bad things?

**Comment by TheDan64** [comment]
I suppose the delete call itself may strictly be safe in that case, but it could still lead to unsafe behavior afterward with the current model.

**Comment by nlewycky** [comment]
If the rust code has other handles referring to the same llvm value under the hood? Yes, then rust can't see that there's an immutable borrow held while a mutable borrow is used (the deletion), and doesn't keep it safe. I hadn't considered that case, thanks for pointing that out!
