### ISSUE TITLE
BasicValueUse::get_user always returns InstructionValue

### ISSUE THREAD

**Issue by nlewycky** [TheDan64/inkwell#162]
**Describe the Bug**
Value users do not always have to be Instructions.

The user of an Instruction must be an Instruction. However, the user of a Function may be a Constant (say, the LLVM IR for a C++ virtual table, a constant array holding the pointers to functions).

**To Reproduce**
This was noticed by inspection of src/values/basic_value_use.rs.

You could create two `GlobalValue`s,  `@A = external global i32` and `@B = constant i32* @A`, then get a use-list of `@B` and get its first use which will be `@A`, then call `get_user` which will call InstructionValue::new on a non-Instruction.

**Expected Behavior**
`get_user` should probably return a BasicValue, or maybe an Either?

**LLVM Version (please complete the following information):**
 - LLVM Version: llvm8-0
 - Inkwell Branch Used: master

**Comment by TheDan64** [comment]
I think returning `BasicValue` makes sense since you can always turn it into an `InstructionValue` afterwards?

**Comment by nlewycky** [comment]
Yes, that sounds right to me.

**Comment by nlewycky** [comment]
Ah, but not a BasicValueEnum. A store instruction uses other values but always has void type, and therefore isn't a BasicValueEnum. We could use AnyValueEnum which I think always works because any void-typed value would be an InstructionValue.
