### ISSUE TITLE
new test failure triggering assertion

### ISSUE THREAD

**Issue by nlewycky** [TheDan64/inkwell#168]
**Describe the Bug**
LLVM has an Align object that stores a non-zero power-of-two alignment. It has asserts to verify this:
```c++
    explicit Align(uint64_t Value) {
      assert(Value > 0 && "Value must not be 0");
      assert(llvm::isPowerOf2_64(Value) && "Alignment is not a power of 2");
      ShiftValue = Log2_64(Value);
      assert(ShiftValue < 64 && "Broken invariant");
    }
```
The new tests for creating a memcpy try creating a memcpy with an alignment of every integer from 0 to 32. It does check whether the verifier finds it, but it's too late in an asserts-build of LLVM.

**To Reproduce**
The place with the assertion, Alignment.h, is new in LLVM 10. Build LLVM 10 with assertions enabled and run the tests.

With a non-asserts build of LLVM 10, you get
```
thread 'test_builder::test_alignment_bytes' panicked at 'alignment of 3 was neither 0 nor a power of 2, yet verification passed for memcpy when it should not have.', tests/all/test_builder.rs:663:13
```

**Expected Behavior**
The inkwell Builder return an Err on any attempt to create a misaligned memcpy or memmove.

**LLVM Version (please complete the following information):**
 - LLVM Version: 10
 - Inkwell Branch Used: master

**Desktop (please complete the following information):**
 - OS: Debian unstable

**Additional Context**
Although the particular path to this assertion is new in LLVM 10, this wasn't intended to be permitted by the API in pre-10 either. LLVM has been storing some alignments in log2 form is some places and not in others. What changed is that LLVM refactored this into a single data type which includes the assertions.

**Comment by TheDan64** [comment]
@nlewycky please see the previous discussion in #158 

CC @rtfeldman - This is what I was worried about lol

**Comment by rtfeldman** [comment]
:sweat_smile: 

My instinct is to go back to the design where `memcpy` and `memmove` return a `Result`, and copy those invariants from the LLVM C++ code. If either alignment value doesn't fit, return `Err`.

How does that sound?

**Comment by TheDan64** [comment]
Yeah, I agree. Just return an error if `aligment != 0 && !alignment.is_a_power_of_two()` (I think zero was valid?)

**Comment by rtfeldman** [comment]
Cool! I'll make a fresh PR for it.
