### ISSUE TITLE
off by one in ObjectFile API iterators

### ISSUE THREAD

**Issue by nlewycky** [TheDan64/inkwell#172]
**Describe the Bug**
There is no API in LLVM Object library C API to clone a section iterator. The `LLVMMoveToNextSection(self.section_iterator)` method returns void, the contents of `self.section_iterator` stay the same but it refers to a different section.

The implementation of `SectionIterator` checks whether the iterator is one past the end and returns None if it is, then creates a new `Section` out of `self.section_iterator`, then advances `self.section_iterator`. However because there is no deep copy, the `Section` is now holding a one-past-the-end iterator and uses that to answer any queries.

The other bug is that the current implementation always skips the first section, because the first `Section` is returning information through the iterator that has been advanced once.

This bug is repeated for the `RelocationIterator` and `SymbolIterator`.

**To Reproduce**
```rust
use inkwell::memory_buffer::MemoryBuffer;
use std::path::Path;

fn main() {
    let mb = MemoryBuffer::create_from_file(Path::new("test.o")).unwrap();
    let obj = mb.create_object_file().unwrap();
    for section in obj.get_sections() {
        dbg!("<section>");
        dbg!(section.get_name());
        dbg!(section.size());
        dbg!(section.get_address());
    }
}
```
will crash on any .o file. You can use `/bin/ls` for instance. Here's a quick dump using `valgrind`:

```
==39244== Invalid read of size 1
==39244==    at 0x4839CC2: __strlen_sse2 (vg_replace_strmem.c:463)
==39244==    by 0x5A2909: std::ffi::c_str::CStr::from_ptr (c_str.rs:1034)
==39244==    by 0x204871: inkwell::object_file::Section::get_name (object_file.rs:113)
==39244==    by 0x203341: objfile::main (main.rs:9)
==39244==    by 0x20409A: std::rt::lang_start::{{closure}} (rt.rs:67)
==39244==    by 0x5A8A07: {{closure}} (rt.rs:52)
==39244==    by 0x5A8A07: do_call<closure-0,i32> (panicking.rs:331)
==39244==    by 0x5A8A07: try<i32,closure-0> (panicking.rs:274)
==39244==    by 0x5A8A07: catch_unwind<closure-0,i32> (panic.rs:394)
==39244==    by 0x5A8A07: std::rt::lang_start_internal (rt.rs:51)
==39244==    by 0x204076: std::rt::lang_start (rt.rs:67)
==39244==    by 0x203B79: main (in /home/nicholas/objfile/target/debug/objfile)
==39244==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
```

**Expected Behavior**
There's a couple ways to fix this in inkwell. We could change `Section` so that it takes a deep copy of the data that it might be asked to return. Or we could the iterator to do a) advance b) check for at-end c) return a `Section`. However, I think we'd need one extra bit of state to not advance the first time, so that we don't skip the first element.

Or we could improve the LLVM API, but that won't help before the release of LLVM 11.

**LLVM Version (please complete the following information):**
 - LLVM Version: 8
 - Inkwell Branch Used: llvm8-0

**Desktop (please complete the following information):**
 - OS: Debian unstable

**Additional Context**
LLVM is being a bit silly here. If the advance function doesn't return a new advanced iterator, it should provide an API to copy an iterator. Ideally there's a way to get the start iterator, the end iterator, and a query for whether we're looking at the last element (not the one-past-the-end iterator).

**Comment by TheDan64** [comment]
Thanks for taking a look, this is definitely not a well-tested part of the crate atm
