### ISSUE TITLE
Access violation when JitFunction is dropped after its Context

### ISSUE THREAD

**Issue by HactarCE** [TheDan64/inkwell#177]
**Describe the Bug**
The line `drop(f)` below crashes the program with an access violation, so `println!("after drop")` is never executed. The program below produces the following output on my machine:
```
call: 42
drop function
error: process didn't exit successfully: `target\debug\inkwell_break.exe` (exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)
```

**To Reproduce**
```rust
use inkwell::context::Context;
use inkwell::execution_engine::JitFunction;
use inkwell::OptimizationLevel;

type JitFnType = JitFunction<unsafe extern "C" fn() -> u8>;

fn main() {
    let f: JitFnType;
    {
        let ctx = Context::create();
        let module = ctx.create_module("m");
        let builder = ctx.create_builder();
        let ee = module
            .create_jit_execution_engine(OptimizationLevel::None)
            .unwrap();
        let func_type = ctx.i8_type().fn_type(&[], false);
        let func = module.add_function("f", func_type, None);
        let bb = ctx.append_basic_block(func, "b");
        builder.position_at_end(bb);
        builder.build_return(Some(&ctx.i8_type().const_int(42, false)));
        func.verify(true);
        f = unsafe { ee.get_function("f") }.unwrap();
    };
    println!("call: {}", unsafe { f.call() });
    println!("drop function");
    drop(f);
    println!("after drop");
}
```

**Expected Behavior**
`drop(f)` should not cause an access violation.

**LLVM Version:**
 - LLVM Version: 8.0
 - Inkwell Branch Used: llvm8-0

**Desktop:**
 - OS: Windows 10

**Additional Context**
In the program where I actually discovered this bug, the error occurred once I tried to execute the JIT-compiled function after returning it; here it is able to survive that, probably because the JIT-compiled program is so simple.

**Comment by TheDan64** [comment]
> ... here it is able to survive that, probably because the JIT-compiled program is so simple.

I think it actually survives because it keeps an `Rc<ExecutionEngine>` alive, so the function is still alive wrt the EE. I think the invalid memory access is the aforementioned `Rc` dropping, but its context is no longer alive.
