### ISSUE TITLE
Build error because of `doesn't have a size known at compile-time`

### ISSUE THREAD

**Issue by tdh8316** [TheDan64/inkwell#178]
# Describe the bug

After running command `cargo update` for my project which depends on this, the build process failed.

This is the output:
```
   Compiling inkwell_internals v0.1.0 (https://github.com/TheDan64/inkwell?branch=llvm10-0#5831cf88)
   Compiling string_cache v0.7.5
error[E0277]: the size for values of type `str` cannot be known at compilation time
   --> E:\rust\.cargo\git\checkouts\inkwell-946411d814d2c9f8\5831cf8\src\execution_engine.rs:472:20
    |
472 |             .field("<unnamed>")
    |                    ^^^^^^^^^^^ doesn't have a size known at compile-time
    |
    = help: the trait `std::marker::Sized` is not implemented for `str`
    = note: to learn more, visit <https://doc.rust-lang.org/book/ch19-04-advanced-types.html#dynamically-sized-types-and-the-sized-trait>
    = note: required for the cast to the object type `dyn std::fmt::Debug`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
error: could not compile `inkwell`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**LLVM Version (please complete the following information):**
 - LLVM Version: 10.0
 - Inkwell Branch Used: llvm10-0

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional Context**
I think this is related to the latest commit (https://github.com/TheDan64/inkwell/commit/802c2422fba6909f6611b99601fc3b3ab857e59f).
After I rolled back my Cargo.lock file and then recompiled inkwell, it was successful.

# Edit
I'm using the latest version of rust: `rustc 1.43.0 (4fb7144ed 2020-04-20)`

**Comment by TheDan64** [comment]
Sorry about that. Should be fixed now.
