### ISSUE TITLE
Looks like it's not possible to call functions

### ISSUE THREAD

**Issue by porky11** [TheDan64/inkwell#186]
I cannot find an equivalent to the [getOrInsertFunction](http://llvm.org/doxygen/classllvm_1_1Module.html#abb107e4edbf05eae92936cba6801c2d9) function.
Also searched the repo for it and didn't see it.
It seems to be necessary to call functions from inside functions without an equivalent.
If it's really missing, it should probably be implemented pretty fast. Else it's not possible to write a real programming language using inkwell.

**Comment by TheDan64** [comment]
The C API doesn't provide a wrapper on `getOrInsertFunction` AFAIK. You're looking a  C++ function.

Instead, you can call [Module::get_function](https://thedan64.github.io/inkwell/inkwell/module/struct.Module.html#method.get_function) and [Module::add_function](https://thedan64.github.io/inkwell/inkwell/module/struct.Module.html#method.add_function)

**Comment by porky11** [comment]
No, that's not what I'm looking for. I want to add a function call inside a function like this:
```
int main(int argc, char **argv) {
    printf("Hello World!"); // this is the function call I'm looking for (not neccessarily a extern call)
}
```

**Comment by TheDan64** [comment]
It's essentially the same thing. You try to get "printf" with `get_function` and if it's not defined then you need to call `add_function` to get the function value (which you can call) even if it's defined elsewhere.

**Comment by porky11** [comment]
Thanks, I hope I can finally continue working :)
