### ISSUE TITLE
RISCV support available?

### ISSUE THREAD

**Issue by chaozju** [TheDan64/inkwell#191]
Hi I am working on cross sompiling [wasmer](https://github.com/wasmerio/wasmer) to RISCV. In which `inkwell`is used to implement `llvm-backend`.
May I get some information from you about whether RISCV triple is supported as long as LLVM-10 has been supported. 
I hope the answer be [yes](https://github.com/TheDan64/inkwell/commit/2a98bcdc4c31bd3d35c712c4c971590ed60cec50)😜.

I didn't find RISCV-related (maybe something like `Target::initialize_riscv64`)api in [inkwell doc](https://thedan64.github.io/inkwell/inkwell/targets/struct.Target.html) while [wasmer build code here](https://github.com/wasmerio/wasmer/blob/081f6250e69b98b9f95a8f62ad6d8386534f3279/lib/llvm-backend/src/code.rs#L8666) goes like below
```rust
match triple {
            #[cfg(target_arch = "x86_64")]
            _ if triple.starts_with("x86") => Target::initialize_x86(&InitializationConfig {
                asm_parser: true,
                asm_printer: true,
                base: true,
                disassembler: true,
                info: true,
                machine_code: true,
            }),
            #[cfg(target_arch = "aarch64")]
            _ if triple.starts_with("aarch64") => {
                Target::initialize_aarch64(&InitializationConfig {
                    asm_parser: true,
                    asm_printer: true,
                    base: true,
                    disassembler: true,
                    info: true,
                    machine_code: true,
                })
            }
            _ => unimplemented!("target {} not supported", triple),
        }
```

**Comment by TheDan64** [comment]
IIRC RISCV was accidentally added as a supported target in LLVM for LLVM 4 - but was actually still experimental. It looks like RISCV is now officially supported as of LLVM 9? So it should be simple enough to re-enable it assuming llvm-sys supports it still

**Comment by chaozju** [comment]
@TheDan64 
First of all Thanks a lot.
I checked my `llc --version` and got
```bash
LLVM (http://llvm.org/):
  LLVM version 10.0.0
  Optimized build.
  Default target: x86_64-unknown-linux-gnu
  Host CPU: skylake
  Registered Targets:
...
    riscv32    - 32-bit RISC-V
    riscv64    - 64-bit RISC-V
...
```
And I am still not sure about how to obtain an `inkwell` api in rust to make use of LLVM for RISC-V

**Comment by chaozju** [comment]
Is it ok that I only implement the `initialize_<target>` api using llvm-sys and re-use other apis in current `inkwell`?

**Comment by TheDan64** [comment]
We already have an `initialize_riscv`: https://github.com/TheDan64/inkwell/blob/master/src/targets.rs#L754

I think it just needs to have LLVM9+ added to the attribute `llvm_versions`. I might have some time to look at this in the near future but not immediately. I'd also be willing to review a PR change.

Ideally it'd be `#[llvm_versions(4, 9..=latest)]` but I don't think it currently supports multiple comma separated values. It also needs a new feature flag for riscv like we have for the other targets: https://github.com/TheDan64/inkwell/blob/master/Cargo.toml#L30-L61

**Comment by TheDan64** [comment]
RISC should now be available in LLVM 9+
