### ISSUE TITLE
Correct usage of globals with build_load?

### ISSUE THREAD

**Issue by KireinaHoro** [TheDan64/inkwell#192]
I'm trying to create some global variables and load from them, but things are not working right, and I'm getting a panic:

```text
    Finished dev [unoptimized + debuginfo] target(s) in 3m 16s
     Running `target/debug/inkwell-test`
thread 'main' panicked at 'internal error: entered unreachable code: The given type is not a basic type.', third-party/inkwell/src/values/enums.rs:269:18
stack backtrace:
...
  13: inkwell::values::enums::BasicValueEnum::new
             at third-party/inkwell/src/values/enums.rs:269
  14: inkwell::builder::Builder::build_load
             at third-party/inkwell/src/builder.rs:368
  15: inkwell_test::CodeGen::jit_compile
             at src/test/inkwell.rs:35
  16: inkwell_test::main
             at src/test/inkwell.rs:54
...
  26: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

I'm trying to achieve the effect of the following C snippet:

```c
#include <stdint.h>
uint64_t test;
uint64_t global_load() {
  test = 42;
  return test;
}
```

The documentation is not quite clear on how to use `add_global` results together with `build_load`. 
 The corresponding rust code, based on the example in README.md is as follows.  I'm using the `llvm10-0` branch.

```rust
use inkwell::builder::Builder;
use inkwell::context::Context;
use inkwell::execution_engine::{ExecutionEngine, JitFunction};
use inkwell::module::Module;
use inkwell::targets::{InitializationConfig, Target};
use inkwell::OptimizationLevel;
use std::error::Error;

/// Convenience type alias for the `global_load` function.
///
/// Calling this is innately `unsafe` because there's no guarantee it doesn't
/// do `unsafe` operations internally.
type Func = unsafe extern "C" fn() -> u64;

struct CodeGen<'ctx> {
    context: &'ctx Context,
    module: Module<'ctx>,
    builder: Builder<'ctx>,
    execution_engine: ExecutionEngine<'ctx>,
}

impl<'ctx> CodeGen<'ctx> {
    fn jit_compile(&self) -> Option<JitFunction<Func>> {
        let i64_type = self.context.i64_type();
        let fn_type = i64_type.fn_type(&[], false);
        let function = self.module.add_function("global_load", fn_type, None);
        let global = self.module.add_global(i64_type, None, "test");
        let basic_block = self.context.append_basic_block(function, "entry");

        self.builder.position_at_end(basic_block);

        let constant = i64_type.const_int(42, false);
        self.builder.build_store(global.as_pointer_value(), constant);

        let ret = self.builder.build_load(global.as_pointer_value(), "ret");

        self.builder.build_return(Some(&ret));

        unsafe { self.execution_engine.get_function("global_load").ok() }
    }
}

fn main() -> Result<(), Box<dyn Error>> {
    let context = Context::create();
    let module = context.create_module("global_load");
    let execution_engine = module.create_jit_execution_engine(OptimizationLevel::None)?;
    let codegen = CodeGen {
        context: &context,
        module,
        builder: context.create_builder(),
        execution_engine,
    };

    let f = codegen
        .jit_compile()
        .ok_or("Unable to JIT compile `global_load`")?;

    unsafe {
        println!("returns: {}", f.call());
        assert_eq!(f.call(), 42);
    }

    Ok(())
}
```

Any help would be appreciated!

**Comment by TheDan64** [comment]
Hmm, I would expect that code to work. Will have to look into it

**Comment by KireinaHoro** [comment]
Are there any updates?  I'm working on a term project making use of inkwell, and the deadline is approaching...

**Comment by TheDan64** [comment]
Hmm. When I try it, I just get a segfault and not a panic.

**Comment by KireinaHoro** [comment]
I think I've got a little bit of progress, but not sure if I'm in the correct way.  First, for the global variable to possibly work, we need an initializer for it.  Otherwise, LLVM would simply generate a store into NULL:

```rust
        global.set_initializer(&i64_type.const_int(0, false));
```

Then, I had to hack the value creation inside `build_load`, to always create an `IntValue`.  That is, to change as follows:

https://github.com/TheDan64/inkwell/blob/84b9666c72ae9f286bfee559d13ac71ec8d1fce9/src/values/enums.rs#L257-L269

into

```rust
   match type_kind {
            LLVMTypeKind::LLVMFloatTypeKind |
            LLVMTypeKind::LLVMFP128TypeKind |
            LLVMTypeKind::LLVMDoubleTypeKind |
            LLVMTypeKind::LLVMHalfTypeKind |
            LLVMTypeKind::LLVMX86_FP80TypeKind |
            LLVMTypeKind::LLVMPPC_FP128TypeKind => BasicValueEnum::FloatValue(FloatValue::new(value)),
            LLVMTypeKind::LLVMStructTypeKind => BasicValueEnum::StructValue(StructValue::new(value)),
            LLVMTypeKind::LLVMPointerTypeKind => BasicValueEnum::PointerValue(PointerValue::new(value)),
            LLVMTypeKind::LLVMArrayTypeKind => BasicValueEnum::ArrayValue(ArrayValue::new(value)),
            LLVMTypeKind::LLVMVectorTypeKind => BasicValueEnum::VectorValue(VectorValue::new(value)),
            _ | LLVMTypeKind::LLVMIntegerTypeKind => BasicValueEnum::IntValue(IntValue::new(value)),
        }
```

That is what has been causing the panic.  This is discovered by printing `type_kind` out: `LLVMBuildLoad` actually returned a `LLVMFunctionTypeKind`, and fell through the match cases.  After the fix and the hack, I can correctly get 42 returned now.  The generated LLVM IR:

```llvm
; ModuleID = 'global_load'
source_filename = "global_load"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"

@test = global i64 0

define i64 @global_load() {
entry:
  store i64 42, i64* @test, align 8
  %ret = load i64, i64* @test, align 8
  ret i64 %ret
}                                                                                                                                                                 
```

Now I'm not sure what went wrong, and what's the correct way to fix this...

**Comment by TheDan64** [comment]
It's not clear to me why `build_load` would return a `FunctionType`... Maybe it's an LLVM 10 bug? It doesn't panic in LLVM 8 as I said earlier.

**Comment by nlewycky** [comment]
Once the external linkage issue was resolved, this testcase looks correct. It works for me with both LLVM 8 and LLVM 10, with debug+asserts builds of llvm.

I have a theory. Is it possible that you might be building inkwell/llvm-sys with one copy of llvm header files etc., but when loading ld.so finds a different version of llvm at startup time?

**Comment by KireinaHoro** [comment]
@nlewycky was actually right; I had LLVM 10 and 11 on the system (Debian, from apt.llvm.org), and `llvm-config` was defaulting to 11.  It was confirmed that llvm-sys was linking against 11 in `cargo build -v`.  I had to set `LLVM_SYS_100_PREFIX` and `LLVM_SYS_100_STRICT_VERSIONING` to manually select LLVM 10.  The testcase works fine then.

Maybe we should update the documents to warn the users about mixing LLVM versions or, even better, pose some checks?

**Comment by TheDan64** [comment]
I'm not sure what can be done about it other than documentation. Though it seems like it should be obvious not to mix and match different LLVM versions
