### ISSUE TITLE
How to use inkwell

### ISSUE THREAD

**Issue by justinfargnoli** [TheDan64/inkwell#207]
Hello, I've been trying to setup inkwell for a side project, but am having some trouble and wanted to reach out to see if someone could help me out.

I'm on macOS 10.15.6. 

I added inkwell to Cargo.toml as the README.md stated, then got the following error message:

```
Checking llvm-sys v100.2.0
error: No suitable version of LLVM was found system-wide or pointed
       to by LLVM_SYS_100_PREFIX.

       Consider using `llvmenv` to compile an appropriate copy of LLVM, and
       refer to the llvm-sys documentation for more information.

       llvm-sys: https://crates.io/crates/llvm-sys
       llvmenv: https://crates.io/crates/llvmenv
   --> /Users/justinfargnoli/.cargo/registry/src/github.com-1ecc6299db9ec823/llvm-sys-100.2.0/src/lib.rs:483:1
    |
483 | / std::compile_error!(concat!(
484 | |       "No suitable version of LLVM was found system-wide or pointed
485 | |        to by LLVM_SYS_", env!("CARGO_PKG_VERSION_MAJOR"), "_PREFIX.
486 | |
...   |
490 | |        llvm-sys: https://crates.io/crates/llvm-sys
491 | |        llvmenv: https://crates.io/crates/llvmenv"));
    | |____________________________________________________^

error: aborting due to previous error

error: could not compile `llvm-sys`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

I then install llvmenv, using `cargo install llvmenv`, and ran `llvmenv build-entry 10.0.0` which then fails with the following error message:

```
-- Builtin supported architectures: i386;x86_64;x86_64h;armv7;armv7k;armv7s;arm64
CMake Error at projects/compiler-rt/test/builtins/CMakeLists.txt:55 (message):
  Target clang_rt.builtins_arm64_osx does not exist


-- Configuring incomplete, errors occurred!
See also "/Users/justinfargnoli/Library/Caches/llvmenv/10.0.0/build/CMakeFiles/CMakeOutput.log".
See also "/Users/justinfargnoli/Library/Caches/llvmenv/10.0.0/build/CMakeFiles/CMakeError.log".
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: CommandError { errno: 1, cmd: "\"cmake\" \"/Users/justinfargnoli/Library/Caches/llvmenv/10.0.0\" \"-DCMAKE_INSTALL_PREFIX=/Users/justinfargnoli/Library/Application Support/llvmenv/10.0.0\" \"-DCMAKE_BUILD_TYPE=Release\"", stdout: None, stderr: None }', /Users/justinfargnoli/.cargo/registry/src/github.com-1ecc6299db9ec823/llvmenv-0.3.0/src/bin/llvmenv.rs:159:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This is preceded by roughly a 100 lines of log outputs to the console. 

I don't exactly know how to proceed from here. Thanks in advance for the help :)

**Comment by jakevossen5** [comment]
I am having the same issue, are you able to share how you resolved it?

**Comment by justinfargnoli** [comment]
I'm having trouble finding out how exactly how I resolved it because I resolved this on my old laptop which is currently having issues.

However, @jakevossen5, I think I resolved this by installing the appropriate version of llvm, I'm on macOS so I used brew, and manually set LLVM_SYS_100_PREFIX with the path to brew's installation of llvm.

**Comment by TheDan64** [comment]
Unfortunately, this is more of an LLVM issue than an inkwell one. I also don't run macOS so I'm not able to be of much help. llvmenv is a great project but needs a lot more polish before I can really recommend using it

**Comment by jakevossen5** [comment]
It also seems like llvmenv is having some trouble with maintainers: https://github.com/termoshtt/llvmenv/issues/72

**Comment by nevi-me** [comment]
If it's helpful to anyone, I installed LLVM manually on Linux/WSL, and set the variable `export LLVM_SYS_100_PREFIX=/usr/lib/llvm-10`. Both llvm-sys and inkwell compile with no issues.
