### ISSUE TITLE
Provide build instructions in README

### ISSUE THREAD

**Issue by mrLSD** [TheDan64/inkwell#209]
**Is your feature request related to a problem? Please describe.**
Currently, if I run:
```
$ git clone ...
$ cd inkwell
$ cargo check # return errors
$ cargo build --examples # return a lot of errorrs
```
I have got a lot of errors.

**Describe the solution you'd like**
Provide step-by-step instructions in **README.md** how to build examples and the project itself.

**Comment by TheDan64** [comment]
Hi, the [usage section](https://github.com/TheDan64/inkwell#usage) already explains that you must provide a cargo feature flag corresponding to your LLVM version. IE `cargo check --features llvm10-0`
