### ISSUE TITLE
Debug Info : GlobalVariableExpression missing

### ISSUE THREAD

**Issue by ghaith** [TheDan64/inkwell#216]
While implementing debug for a custom language, I noticed that some of the LLVMDIBuilder methods are not implemented in inkwell, most notabley the `LLVMDIBuilderCreateGlobalVariableExpression`
I was also not able to implement it myself as a workaround (in an unsafe manner) since metadata_ref is private so I can't reach any of the llvm-sys structures.

Would be possible, until the extra methods are available, to expose a `get_metadata_ref()` or something similar to be able to workaround these issues.
I will try to get a PR going for the missing debug methods, but I'm not sure when I would be able to contribute this.

**Comment by ghaith** [comment]
I tried to implement the missing parts but it looks to me like llvm-sys is still missing some methods to be able to correctly use GlobalVariables, most notably was the [addDebugInfo](https://llvm.org/doxygen/classllvm_1_1GlobalVariable.html#aebcc339b418cae92442b394b33359705), I am not sure if I just missed it, but I guess there would not be much to do on the inkwell side until that is contributed. I will look at if I can find what's missing in llvm-sys and implement it.

**Comment by TheDan64** [comment]
If it's provided by the C API and llvm-sys is missing it, then llvm-sys should add it. If it is not provided by the C API then there's nothing to be done about it

**Comment by TheDan64** [comment]
I would much rather see a PR to add support for any functions we're missing rather than expose inkwell internals

**Comment by ghaith** [comment]
It does look like the method is not in the C API at first glance. I looked at the Clang implementation and they seem to be using the C++ class for that which makes sense. I will try to take a look at how rust solved it in rustc, do you know if they built an extra C wrapper around the missing functionality? I was contemplating that as a possible solution, writing a C Wapper for some of the missing C++ functions that we need and then adding a Rust Wrapper around that but that would be a lot of maintenance work. But assuming that works would you be open to integrating yet another LLVM binding in Inkwell? I might also try to contribute such a wrapper to llvm-sys first but since it's no longer the C-API it might be out of their scope.

**Comment by TheDan64** [comment]
I'm not sure. Interfacing with C++ is tricky and can get hairy pretty quickly. I'd like to avoid doing so if possible and contain inkwell to the C API. I wonder if requesting they add this to the C API might be a better approach, although that would obviously take a while

**Comment by ghaith** [comment]
I found a way to do this using the C API
The methods we are looking for are `LLVMDIBuilderCreateGlobalVariableExpression`, `LLVMDIBuilderCreateConstantValueExpression` to create a global variable debug expression 
To add it to the actual global value object we need to add a "dbg" metadata so something like the instruction's `set_metadata` function for globalvalues should work but we currently don't have a way to convert a DI element to its a metadata (or did i miss that?) I was working on a change to add this, but didn't finish it yet. I'll try to push my local state for now and will create a pull request once it's working. I'm not certain about how/when to add new traits here maybe an AsMetadataValue trait would be helpful here, and I'm not sure about any contribution guidelines you have, I will try to follow your architecture as much as I can for this and hope the review isn't too aweful :)

**Comment by ghaith** [comment]
My current branch where i'm trying this: https://github.com/ghaith/inkwell/tree/llvm10-0-global_debug it is not based on master yet so that i can try it quickly the final branch will be based on master.
Do you usually cherrypick changes to version branches when needed btw?

Here's a gist with an example of how I thought I could use the new code:
https://gist.github.com/ghaith/05b2feecb079196aad44c77c38e69bda
It does not work yet.

**Comment by TheDan64** [comment]
You should be working off master - the version branches are deprecated and no longer supported. They remain only so existing users' projects don't break suddenly.

**Comment by ghaith** [comment]
Closing the issue since we now have the pull request merged
