### ISSUE TITLE
Add support for LLVM11

### ISSUE THREAD

**Issue by baszalmstra** [TheDan64/inkwell#217]
**Is your feature request related to a problem? Please describe.**
[Mun](https://github.com/mun-lang/mun) cant upgrade beyond LLVM8 due to a bug introduced in LLVM9. This has been fixed from LLVM11 onwards. Inkwell doesnt support LLVM11 yet.

**Describe the solution you'd like**
We would like to be able to use LLVM11 with Inkwell.

**Describe possible drawbacks to your solution**
Since this can be implemented with a feature flag, I dont think there will be drawbacks for other users. 

**Describe alternatives you've considered**
We could use the llvm-sys bindings directly, support for LLVM11 has already landed there. For obvious reasons Id rather not.

**Additional context**
Nope

**Comment by ghaith** [comment]
I would like to help with this.
I took a look at the changes in LLVM 11 and there are no deprecations on the Frontend level at first glance. There might be some on the Backend, I don't know how much of the backend API is supported in inkwell. 
Do you have a plan on how to start this? I'm open to help with issues once you devide them. I can also probably take a look at the weekend at the required work.

**Comment by TheDan64** [comment]
The first step is to add in llvm-sys 11 and see what breaks. Some relevant locations:

* https://github.com/TheDan64/inkwell/blob/master/Cargo.toml#L27
* https://github.com/TheDan64/inkwell/blob/master/Cargo.toml#L43
* https://github.com/TheDan64/inkwell/blob/master/Cargo.toml#L98
* https://github.com/TheDan64/inkwell/blob/master/src/lib.rs#L65
* https://github.com/TheDan64/inkwell/blob/master/internal_macros/src/lib.rs#L23

From there fix any breakage. There are a couple locations that always break and just need a `cfg` to include `llvm11-0`, though I can't point to them by memory. If you run into any hard issues, feel free to bring it up here
