### ISSUE TITLE
Publish beta1 to crates.io

### ISSUE THREAD

**Issue by baszalmstra** [TheDan64/inkwell#226]
**Is your feature request related to a problem? Please describe.**
For [Mun](https://github.com/mun-lang/mun), we would really like to make another release based on the latest inkwell version. However, we would really like to use some of the features that have recently landed.

- https://github.com/TheDan64/inkwell/pull/208
- LLVM version agnostic release: https://github.com/TheDan64/inkwell/issues/154

**Describe the solution you'd like**
It would be great if you could cut another (release candidate) release.

**Describe possible drawbacks to your solution**
I understand that this is not ideal but it looks like v0.1.0 is still quite far away.

**Describe alternatives you've considered**
An alternative would be to fork the repository and publish that ourselves but that seems very far from ideal. I really don't want to do that.

**Comment by TheDan64** [comment]
Sure, that can be done. But it wouldn't be a release candidate since it's not ready for release. Also, would like to get #224 merged before doing so

**Comment by baszalmstra** [comment]
Thats great! Thanks!

**Comment by baszalmstra** [comment]
Hey @TheDan64! Do you have an indication on when you might publish the beta?

**Comment by TheDan64** [comment]
Trying to get https://github.com/TheDan64/inkwell/pull/221 fixed and merged first since it's really close to being done. Hopefully this weekend or next. Can't give an exact date but relatively soon

**Comment by TheDan64** [comment]
Didn't get to fixing the aforementioned PR unfortunately but I've gone ahead and published a new version: `0.1.0-beta.1`

**Comment by baszalmstra** [comment]
Thanks for publishing, I appreciate it a lot!

I've run into a small issue though, the release contains a file called `nul` (see https://docs.rs/crate/inkwell/0.1.0-beta.1/source/nul). This appears to be a reserved filename on windows which causes cargo to fail to download the release on windows: 
```
Caused by:
  unable to get packages from source

Caused by:
  failed to unpack package `inkwell v0.1.0-beta.1`

Caused by:
` failed to unpack entry at `inkwell-0.1.0-beta.1/nul

Caused by:
` failed to unpack `C:\Users\username\.cargo\registry\src\github.com-1ecc6299db9ec823\inkwell-0.1.0-beta.1\nul

Caused by:
` into `C:\Users\username\.cargo\registry\src\github.com-1ecc6299db9ec823\inkwell-0.1.0-beta.1\nul

Caused by:
  The filename, directory name, or volume label syntax is incorrect. (os error 123)
```

Any idea what that file is?

**Comment by TheDan64** [comment]
No clue. Ugh. Gonna try and re-publish

**Comment by TheDan64** [comment]
`0.1.0-beta.2` published. Seems to be free of that artifact

**Comment by baszalmstra** [comment]
Thanks! That did fix it. :)

**Comment by seanyoung** [comment]
I'd like to suggest that  `0.1.0-beta.1` is yanked

**Comment by TheDan64** [comment]
Good idea. Done.
