### ISSUE TITLE
Question: Purpose of `name` parameter in methods of `Builder` struct?

### ISSUE THREAD

**Issue by justinfargnoli** [TheDan64/inkwell#228]
What is the purpose of the `name` parameter on many of the methods of the `Builder` struct?

For example, [Builder.build_call()](https://thedan64.github.io/inkwell/inkwell/builder/struct.Builder.html#method.build_call) take the parameter `name: &str`. The example which follows it supplies the argument `"call"`. 

Other methods which take a `name` parameter and have examples also pass the name of the thing being built. I'm assuming that this is just done for the sake of the examples. Thus, I'm still having trouble figuring out what its purpose is. 

I'm new to working with LLVM and inkwell, so any help is appreciated :)

**Comment by TheDan64** [comment]
Depends on the function in question, but most of the time it's an identifier for the LLVM IR. You'll only really see it for `build_call` if the return type is not void I think

**Comment by TheDan64** [comment]
For example the IR might look something like this:

```ir
%get_pi = tail call float @get_pi()
```

for

```rust
    let context = Context::create();
    let module = context.create_module("sum");
    let builder = context.create_builder();

    let f32_type = context.f32_type();
    let fn_type = f32_type.fn_type(&[], false);

    let function = module.add_function("get_pi", fn_type, None);

    // ...

    let pi2_call_site = builder.build_call(function, &[], "get_pi");
```

where `%get_pi` is the identifier
