### ISSUE TITLE
Why aren't datalayout publicly constructable

### ISSUE THREAD

**Issue by Janonard** [TheDan64/inkwell#231]
**Is your feature request related to a problem? Please describe.**
I'm working on a script that modifies LLVM IR code to run on a platform that isn't supported by Rust and for that, I need to change the data layout of the module. Now I found that the methods for creating a `DataLayout` aren't exposed as public methods and I'm wondering why? They aren't unsafe and from what I can tell, they don't do that nasty stuff, so why can't I use them?

**Describe the solution you'd like**
Make methods for the creation of `DataLayout`, `LLVMString` and possibly other things public.

**Describe possible drawbacks to your solution**
I don't know. That's why I'm asking!

**Describe alternatives you've considered**
In order to just get going, I will just fork the project and make all methods public that I need. It's a workaround, but not a proper solution

**Comment by Janonard** [comment]
Nevermind, I'm going to solve the problem in another way

**Comment by TheDan64** [comment]
I'm not sure I follow. Pointing out which methods you'd like to see public would be helpful. Assuming you're talking about, eg, `DataLayout::new_owned` and `DataLayout::new_borrowed`, then yes, they could potentially be unsafe if used incorrectly outside the crate. This is why they are not exposed - we only use them in very specific safe ways in inkwell.

OTOH, we could add a safe interface that takes an owned string perhaps if we can validate that LLVM's parse was successful
