### ISSUE TITLE
LLVMParseIRInContext support

### ISSUE THREAD

**Issue by raviqqe** [TheDan64/inkwell#233]
**Is your feature request related to a problem? Please describe.**

- [LLVMParseIRInContext C API](https://docs.rs/llvm-sys/110.0.1/llvm_sys/ir_reader/fn.LLVMParseIRInContext.html) is not supported.

**Describe the solution you'd like**

- The cleanest way to support the API is probably adding another method to the `Context` struct.
  - e.g. `Context::parse_ir(ir: &str) -> Module`

**Additional context**

I want to use the `musttail` flag of `call` instructions but it's not supported by the LLVM C API currently. So I want to just replace all `tail` calls into `mustail` ones in IR by regex matching. :p

**Comment by TheDan64** [comment]
[`create_module_from_ir`](https://thedan64.github.io/inkwell/inkwell/context/struct.Context.html#method.create_module_from_ir) calls `LLVMParseIRInContext`

**Comment by raviqqe** [comment]
Oh I missed it! Thanks!

**Comment by TheDan64** [comment]
Sure thing! See the `MemoryBuffer` docs for more info on how to create one: https://thedan64.github.io/inkwell/inkwell/memory_buffer/struct.MemoryBuffer.html
