### ISSUE TITLE
Bug - f64 Array

### ISSUE THREAD

**Issue by Sheepsody** [TheDan64/inkwell#234]
Hi,
I have been trying to figure out why this fails, and why I can not reproduce the example in the code.
Thanks,

**Describe the Bug**
Cannot reproduce [int array example](https://github.com/TheDan64/inkwell/blob/1c5e323dc185310741dc9c52f78490505b5298c8/src/builder.rs#L1319) with f64

**To Reproduce**
```rust
let array_type = self.f64_type.array_type(length);
let array_alloca = builder.build_alloca(array_type, "alloca");
builder
            .build_load(array_alloca, "array_load")
            .into_array_value()
self.builder
             .build_insert_value(array, self.f64_type.const_float(1.0), 4, "insert");
self.builder
             .build_extract_value(array, 4, "extract")
             .unwrap()
             .into_float_value()
```
-> this yelds   `0.00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000069525581899026`

**Expected Behavior**
Should yield `1.0`

**LLVM Version (please complete the following information):**
 - LLVM Version: [e.g. 8.0]
 - Inkwell Branch Used: [e.g. llvm8-0]

**Desktop (please complete the following information):**
 - OS: Ubuntu 18

**Additional Context** : LLVM IR Code
define double @jit() {
entry:
  %a = alloca [10 x double]
  %array_load = load [10 x double], [10 x double]* %a
  %insert = insertvalue [10 x double] %array_load, double 1.000000e+00, 4
  %extract = extractvalue [10 x double] %array_load, 4
  ret double %extract
}

**Comment by TheDan64** [comment]
I think this is just how float rounding works and not an inkwell bug

**Comment by Sheepsody** [comment]
Sorry there was an issue in the report... The excected value was 1.0, and the result seems to be the same whatever I fix it to.
Thanks for your answer!
