### ISSUE TITLE
Escape hatch for when Inkwell is not 1-to-1 with the LLVM API

### ISSUE THREAD

**Issue by willtunnels** [TheDan64/inkwell#235]
**Is your feature request related to a problem? Please describe.**
Inkwell's `StructType::set_body` will only set the body of a type if it is opaque. Once the body has been set this means trying to set it again will (silently)  fail, since setting the body of an opaque type makes it no longer opaque. I'm not sure if this is an explicit choice on Inkwell's part to provide an API which differs from LLVM's or if, from a correctness standpoint, `LLVMSetBody` can only be called on a type once. (This is something that might be worth discussing in a separate issue of its own). This came up for me when handling recursive array types in my language. I found a work around for this in my particular case that involved foward declaring opaque structs for any anonymous sums types. I think this points to a missing feature in the Inkwell API.

**Describe the solution you'd like**
It should be possible to construct Inkwell types from raw LLVM types and to get the underlying raw LLVM type from an inkwell type. This would mean adding methods to Inkwell's type types, value types, modules, targets, etc.

**Describe possible drawbacks to your solution**
Like many escape hatches, this provides a dangerous tool to the user. It is possible they could cause the underlying LLVM types to take on a state Inkwell assumes they cannot.

Regardless, I think this API would make users feel more comfortable adopting Inkwell. Even if there is some tiny aspect of the library that doesn't fit their use case, they could always work around it. Of course, this API would come with "warning labels" attached.

**Comment by TheDan64** [comment]
IIRC this is an LLVM correctness issue - you can't set the body this way with a non-opaque struct. I could be wrong though, haven't looked at the underlying LLVM code in a while.

Adding raw getters/setters defeats the point of having a safe abstraction over LLVM. If there's missing functionality, the solution is not to have an escape hatch, but to upstream the necessary changes into inkwell (provided we've come to an agreement on those changes)
