### ISSUE TITLE
Garbage Collection

### ISSUE THREAD

**Issue by Dominilk** [TheDan64/inkwell#245]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
I’m writing a general purpose feature-rich programming language and need access to LLVMs garbage collection utilities/features.

**Describe the solution you'd like**
A safe API wrapper around LLVMs gc features.

**Describe possible drawbacks to your solution**
How might this solution hinder other components or users if implemented?
Can’t think of any to be honest.
**Describe alternatives you've considered**

**Additional context**
/

**Comment by TheDan64** [comment]
Which LLVM C API functions in particular are you looking to see supported?

**Comment by Dominilk** [comment]
This article gives an overview of a lot of useful functions: https://llvm.org/docs/GarbageCollection.html#custom-gc-strategies
------
So it'd be great to see them supported.

**Comment by TheDan64** [comment]
That doesn't seem to list the C API functions so unfortunately it's not very useful as they may not be supported by the C API.

I did just remember there's a `set_gc` method for function values: https://thedan64.github.io/inkwell/inkwell/values/struct.FunctionValue.html#method.set_gc

**Comment by Dominilk** [comment]
Thanks. I need to progress a little bit with the language, then I will get back with more information. Still, thanks a lot! I will close the issue for now and then re-open it when it becomes relevant again.
