### ISSUE TITLE
Support For LLVM version 12.0.

### ISSUE THREAD

**Issue by amm834** [TheDan64/inkwell#249]
**Describe the solution you'd like**

LLVM is upgraded to Version 12.0.
Please upgrade this.

https://releases.llvm.org/

**Comment by TheDan64** [comment]
This is blocked by llvm-sys not having v12 bindings yet

**Comment by TheDan64** [comment]
Correct. Inkwell is dependant on the `llvm-sys` crate, which has not yet released bindings for LLVM 12

**Comment by Raspberry1111** [comment]
It appears that there is [now a version of `llvm-sys`](https://crates.io/crates/llvm-sys/120.0.0) with LLVM 12 bindings

**Comment by seanyoung** [comment]
Now that llvm 12 support has been merged, can we have a crates.io release please? Something like 0.1.0-beta3.

I have tested llvm 12 support with [Solang](https://github.com/hyperledger-labs/solang) and it all looks fine to me.

**Comment by TheDan64** [comment]
I'd like to wait until we get a couple more of the recent open PRs merged
