### ISSUE TITLE
GlobalValue almost unusable

### ISSUE THREAD

**Issue by nicokoch** [TheDan64/inkwell#26]
Hey, I noticed the `GlobalValue` struct cannot be used with `Builder` methods, because it does not implement BasicType.
I also don't notice a function to get a `PointerValue` from a `GlobalValue`.

Unless I'm missing something, this should probably get fixed.

**Comment by TheDan64** [comment]
Hi! Thanks for opening this issue.

I could be mistaken, but I don't believe `GlobalValue` is always a `PointerValue`. For this reason its `get_initializer` method returns an `Option<BasicValueEnum>` (if it has a value assigned to it). That enum does implement the `BasicValue` trait (I think you meant Value, not Type? If you did mean Type, there is a `BasicValueEnum` -> `BasicTypeEnum` method `get_type`) and can be converted to a `PointerValue` if it is indeed one.

That said, it might be correct for us to implement `BasicValue` for `GlobalValue` if `GlobalValue` can't be non `BasicValue` things like metadata and an uninitialized `GlobalValue` doesn't generate LLVM errors when attempting to be used as if it was initialized. That last bit should be able to be ingrained into the type system eventually(#8) though.

**Comment by nicokoch** [comment]
In the curren state, one cannot store anything to a `GlobalValue` at runtime (because it cannot be used as an argument to `build_store`). Also, there's no way to read a `GlobalValue`, except the initial state.

**Comment by TheDan64** [comment]
Ah, I think I'm starting to understand. So, `get_initializer` will always return the initialized value (if any) even if it was already overridden to a new value at runtime?

Today, `GlobalValues` are only created from `BasicType`s/`BasicValue`s. I think it would be great to validate that assumption and if correct, have `GlobalValue` impl the `BasicValue` trait, which should resolve this problem.

Just let me know if you're interested in taking this on, otherwise I will probably get to it sometime this weekend.

**Comment by nicokoch** [comment]
I might be able to tackle this soon, we will see :).

However, I suggest simply adding a method `GlobalValue::as_pointer()`, which will return a `PointerValue`. The LLVM documentation states that GlobalValue is always a pointer: http://llvm.org/doxygen/classllvm_1_1GlobalValue.html#a92041fc7f781ba4fe708eec99139b72f .

This way, we also don't have to add another variant to BasicValueEnum/AnyTypeEnum.

**Comment by TheDan64** [comment]
So, LLVM really confuses me. I thought I read it should always be a pointer too, but when writing tests I found that it could be other types too: https://github.com/TheDan64/inkwell/blob/master/tests/test_values.rs#L760

Is the difference maybe that the initializer is allowed to be a non pointer (the pointed to value, skipping the indirection), but a `GlobalValue` itself is just a `PointerValue`? I think `GlobalValue::as_pointer()` makes sense if so. And implementing `BasicValue` for `GlobalValue` still makes sense, as it is still true.

Regarding visibility, I think `GlobalValue` might not be a long lived construct in Inkwell. Invoking SubTypes again here (#8), I think this could eventually be in the type system as `PointerValue<Global, T>` vs `PointerValue<Local, T>`

**Comment by nicokoch** [comment]
Yes, I think it's because the initializer can be a non-pointer. The GlobalValue itself will always be a pointer.

**Comment by nicokoch** [comment]
Another possibility is to `Deref` GlobalValue to PointerValue. I'm not for or against any of the suggestions, just throwing some ideas around.

**Comment by TheDan64** [comment]
True, that could work. But I've generally found manual impls of the `Deref` trait to be a bit of a wart in rust. Possibly due to order of operations? I usually have to wrap it in parenthesis first: `(*wrapper).foo()` when I expect `*wrapper.foo()` to work

**Comment by TheDan64** [comment]
Going to work on this issue next, as it is a usability issue.
