### ISSUE TITLE
Missing "merge functions pass" from PassManager

### ISSUE THREAD

**Issue by jrolli** [TheDan64/inkwell#267]
**Is your feature request related to a problem? Please describe.**
Yes because generated code often contains functions which are near identical at an ISA level which differ only in type information.  LLVM has exposed an optimization pass (`mergefunc`) in its C API (as `LLVMAddMergeFunctionsPass`) since version 10.0 that is intended to address this issue by collapsing duplicate functions into a single instance.  This can significantly save on final compiled size.  There is a detailed overview of the pass [here](https://www.llvm.org/docs/MergeFunctions.html#introduction).

**Describe the solution you'd like**
The function is exposed in `llvm-sys` and can be passed through just like the other functions from `ipo.h`.

**Describe possible drawbacks to your solution**
This approach does not create a systematic approach to tracking future changes in `ipo.h` (or any other passes exposed by `llvm-sys`).

**Describe alternatives you've considered**
Alternative is to bypass Inkwell and work with `llvm-sys` directly or run the pass via shelling out to `opt`.

**Additional context**
None

**Comment by pejato** [comment]
Hi @TheDan64 / @jrolli, looks like a PR was merged to resolve this. Can the issue be closed now?

**Comment by TheDan64** [comment]
Good catch, thanks!
