### ISSUE TITLE
Allow conversion from instruction value to phi value, if not already possible

### ISSUE THREAD

**Issue by muke101** [TheDan64/inkwell#274]
I want to take an InstructionValue, check if it's a phi instruction, and then create a PhiInstruction struct pointing to the same underlying LLVM value. I've looked through all the relevant parts in the documentation and I can't find a way to achieve this, so if I'm correct in that it's not possible then adding this functionality would be very helpful. If it is already possible I'd appreciate being shown how.

Thanks.

**Comment by TheDan64** [comment]
hmm, it might be possible to implement
