### ISSUE TITLE
Allow public calls to AsValueRef trait

### ISSUE THREAD

**Issue by muke101** [TheDan64/inkwell#275]
I need to read the LLVMValueRef fields of LLVM objects I'm working with in my project that uses inkwell, and I don't think this is a very uncommon need either. The LLVM C API is significantly reduced compared to the regular API in areas and to use it in it's full capacity you occasionally have to wrap it's function with your own C code, which take LLVMValueRef values.

The obvious solution would be to make the implementations of the AsValueRef trait public. I understand writing to or even just holding this value can be unsafe but I don't think that warrants completely disallowing it altogether when there are very reasonable use cases for doing so.

**Comment by TheDan64** [comment]
> I think the obligation of safe code should be on the programmer, not the library author.

This goes against Rust's values and this project's. Yes, unsafe methods can/should be allowed where it makes sense. But the whole point of wrapping an unsafe C library is to make it as safe and air-tight as possible. That *is* the obligation of the library, not the consumer.

That said, I will leave this ticket open and remain open to the idea of having unsafe getters in the future

**Comment by muke101** [comment]
> But the whole point of wrapping an unsafe C library is to make it as safe and air-tight as possible. That is the obligation of the library,

Well to be clear I never meant in terms of unsafe code that the programmer isn't explicitly aware is unsafe, just that it should be the programmers choice when they need to use unsafe code and when they don't. As it stands right now it's essentially a choice that's been made by the library. And further from the general values of the project, at the end of the day there really is just needed functionality that can't be used without unsafe code. I just don't think this library could be posed as a serious solution to using LLVM with Rust if it has the limited scope of LLVM's C wrapper baked in. 

I hope you make the decision to allow access to these fields in some way soon. In the mean time I guess I'll just have to fork the repo to include it for use with my own project, but that can't be a long term solution.

**Comment by ghaith** [comment]
I would like to add my +1 to this issue.
My view is that there are functions that are not exposed through the C-API, where calling into a C++ wrapper is necessary. In its current state inkwell makes this impossible.
I think an **_unsafe_** method to get the LLVM internal values could make such situations possible.
If unsafe getters are not desirable, an option might be to provide the references via closures/functions and keep the entire operation unsafe.
Exposing the getters behind a feature flag also seems reasonable to me.
Would you be open to a PR for this? (Initially unsafe getters behind a feature flag)

**Comment by TheDan64** [comment]
Alright, let's go ahead with unsafe getters which are hidden behind a feature flag
