### ISSUE TITLE
Expose TargetOptions FunctionSections

### ISSUE THREAD

**Issue by bhansconnect** [TheDan64/inkwell#305]
So there is a chance I just missed this and it is already exposed in some way, but to my knowledge the emitting function sections is not exposed in inkwell. The value I am talking about is [here](https://llvm.org/doxygen/classllvm_1_1TargetOptions.html#abb646e2505e21a891497f665187963b3) in the llvm documentation. It essentially enables emitting a text section for every function in the application. I am wondering:

1. If I just missed this somehow and it is actually possible to specify with inkwell currently.
2. What it would take to expose this?

**Comment by TheDan64** [comment]
Is this what you're looking for, maybe? https://thedan64.github.io/inkwell/inkwell/values/struct.GlobalValue.html#method.set_section

**Comment by bhansconnect** [comment]
I just dug into this some more. I guess I wasn't thinking about the limitation of what is exposed by the C api. Any, it looks like you are correct. `set_section` will enable me to do what I want. Function sections just automates setting the section with a generated name. I guess I will just need to manually generate the names whenever I create a function. Thanks for the pointer.
