### ISSUE TITLE
Implement const_array method on basicValueEnum and a flat version on ArrayValues

### ISSUE THREAD

**Issue by Isaac-Leonard** [TheDan64/inkwell#307]
**Is your feature request related to a problem? Please describe.**
Currently when creating arrays from an ast I must know what type of array I want to create instead of being able to do it generically.
So for example:
```
let array=get_some_array_as_basic_value_enum();
array.into_array_type().get_element_type().into_int_type()
    .const_array(elements.as_slice());
```
This requires me to know that the array will be ints and also requires me to get the element type than create the array from that.

**Describe the solution you'd like**
I'd like to either simply call const_array on BasicValueEnums so I could do:
```
let array=get_some_array_as_basic_value_enum();
array.into_array_type()get_element_type()
    .const_array(elements.as_slice());
```
Or even better:
```
let array=get_some_array_as_basic_value_enum();
array.into_array_type()
    .const_array_inplace(elements.as_slice());

```

**Describe possible drawbacks to your solution**
I'm not sure if there might be some drawbacks or limits with generics that makes this impossible or difficult to implement but as elements is already a slice of BasicValueEnums I don't think this is the case.
Edit: I meant that elements could be a slice of BasicValueEnums sorry.
**Describe alternatives you've considered**
Currently I plan to write my own function to do this by matching on the get_element_type value.

**Comment by TheDan64** [comment]
I'm not sure that `const_array` makes sense on `BasicValue`/`Enum`, since there are invalid variants like Vector?

**Comment by Isaac-Leonard** [comment]
Yeah your right, I quickly came across that issue when attempting to implement my own function to do it.
some things like pointers to arrays seem to give an use of instruction is not an instruction error from LLVM.
Maybe having some sort of primitive value enum might work but that could make the over all api more complex.
