### ISSUE TITLE
Pattern of interior mutability / dereferencing `*mut` pointers from immutable `&self` safe?

### ISSUE THREAD

**Issue by pablosichert** [TheDan64/inkwell#319]
Hey there 👋

While collaborating on https://github.com/TheDan64/inkwell/pull/292, the discussion in https://github.com/leifhelm/inkwell/commit/8643148 showed that there might be a larger issue in inkwell in regards to how raw pointers are handled. In summary, dereferencing `*mut` pointers from immutable `&self` can be unsound and this a heavily used pattern in inkwell today.

Structs should store [`NonNull<T>`](https://doc.rust-lang.org/std/ptr/struct.NonNull.html) with `T` = `LLVMOpaque...` instead of a plain `LLVM...Ref` which is a `*mut` pointer to the opaque value. `NonNull` provides the methods `as_ref<'a>(&self) -> &'a T` and `as_mut<'a>(&mut self) -> &'a mut T`, and will make sure that no mutable reference is obtained from an immutable `&self`.

The following illustrates why this is a problem conceptually.

Imagine if the LLVM API was implemented in C++ like the following (the details of the implementation do not matter, and you shouldn't make any assumptions of it other than the public functions):

```rust
mod c_api {
    struct Context {
        modules: Vec<Module>,
    }

    impl Context {
        pub fn new() -> Self {
            Self {
                modules: Vec::with_capacity(1),
            }
        }

        pub fn add_module(&mut self) -> &mut Module {
            let len = self.modules.len();
            self.modules.push(Module::new(len));
            &mut self.modules[len]
        }
    }

    struct Module {
        id: usize,
    }

    impl Module {
        pub fn new(id: usize) -> Self {
            Self { id }
        }

        pub fn print(&self) {
            println!("My id is {}!", self.id);
        }
    }

    #[repr(C)]
    #[derive(Copy, Clone)]
    pub struct ContextRef(*mut Context);

    #[repr(C)]
    #[derive(Copy, Clone)]
    pub struct ModuleRef(*mut Module);

    #[no_mangle]
    pub extern "C" fn context_new() -> ContextRef {
        ContextRef(Box::into_raw(Box::new(Context::new())))
    }

    #[no_mangle]
    pub unsafe extern "C" fn context_destroy(context: ContextRef) {
        Box::from_raw(context.0);
    }

    #[no_mangle]
    pub unsafe extern "C" fn context_add_module(context: ContextRef) -> ModuleRef {
        let context = &mut *context.0;
        ModuleRef(context.add_module())
    }

    #[no_mangle]
    pub unsafe extern "C" fn module_print(module: ModuleRef) {
        let module = &mut *module.0;
        module.print()
    }
}
```

and inkwell currently wraps them similar to this:

```rust
mod rust_api {
    use crate::c_api::{
        context_add_module, context_destroy, context_new, module_print, ContextRef, ModuleRef,
    };
    use std::marker::PhantomData;

    #[repr(transparent)]
    pub struct Context<'a>(ContextRef, PhantomData<&'a ()>);

    impl<'a> Context<'a> {
        pub fn new() -> Self {
            Self(context_new(), PhantomData)
        }

        pub fn create_module(&self) -> Module<'a> {
            unsafe { Module(context_add_module(self.0), PhantomData) }
        }
    }

    impl<'a> Drop for Context<'a> {
        fn drop(&mut self) {
            unsafe { context_destroy(self.0) }
        }
    }

    pub struct Module<'a>(ModuleRef, PhantomData<&'a ()>);

    impl<'a> Module<'a> {
        pub fn print(&self) {
            unsafe { module_print(self.0) }
        }
    }
}
```

you'd then be allowed to run:

```rust
fn main() {
    let context = rust_api::Context::new();

    let module1 = context.create_module();
    module1.print();

    let module2 = context.create_module();
    module2.print();

    // The following code compiles and runs, but is undefined behavior!

    module1.print(); // Prints garbage since the `modules` array in `context`
                     // got reallocated after we added `module2` and the
                     // original reference to `module` is no longer valid.

    drop(context); // Should not be allowed since we still hold references owned
                   // by the context.

    module2.print(); // Prints garbage since `module2` has been deallocated when
                     // dropping `context`.
}
```

if the wrapper was implement like this instead:

```rust
mod rust_api {
    use crate::c_api::{
        context_add_module, context_destroy, context_new, module_print, ContextRef, ModuleRef,
    };

    pub struct Context {
        context: ContextRef,
        modules: Vec<Module>,
    }

    impl Context {
        pub fn new() -> Self {
            Self {
                context: context_new(),
                modules: Default::default(),
            }
        }

        pub fn create_module(&mut self) -> &mut Module {
            let len = self.modules.len();
            self.modules
                .push(Module(unsafe { context_add_module(self.context) }));
            &mut self.modules[len]
        }
    }

    impl Drop for Context {
        fn drop(&mut self) {
            unsafe { context_destroy(self.context) }
        }
    }

    pub struct Module(ModuleRef);

    impl Module {
        pub fn print(&self) {
            unsafe { module_print(self.0) }
        }
    }
}
```

the compiler would correctly reject these issues:

```rust
fn main() {
    let mut context = rust_api::Context::new();

    let module1 = context.create_module();
    module1.print();

    // Compiler error:
    // cannot borrow `context` as mutable more than once at a time
    // main.rs(110, 19): first mutable borrow occurs here
    // main.rs(120, 5): first borrow later used here
    let module2 = context.create_module();
    module2.print();

    module1.print();

    // Compiler error:
    // cannot move out of `context` because it is borrowed
    // move out of `context` occurs here
    // main.rs(117, 19): borrow of `context` occurs here
    // main.rs(129, 5): borrow later used here
    drop(context);

    module2.print();
}
```

The resulting issues are very hard to track down since the code will run most of the time, unless interior mutation actually occurs and affects the running program (in my example this has been constructed by reserving a capacity of 1 for the `Vec` only and forcing it to reallocate). But the whole point of Rust is to prevent this at compile time. I can imagine that many of the [segfault related issues](https://github.com/TheDan64/inkwell/issues?q=segfault+is%3Aopen) boil down to this.

I know that this will likely require redesigning quite a lot of the APIs to conform with the mutability invariants, but that's the only way to make sure we don't run into random segfaults when running inkwell.

**Comment by leifhelm** [comment]
`llvm_sys` needs raw pointers. Reference to the underlying opaque values should not be needed. So I see no benefit of using `NonNull<T>`.

I think the real discussion is which methods should take `&mut self` and which just `&self` to better reflect the underlying mutations.

**Comment by pablosichert** [comment]
> `llvm_sys` needs raw pointers. Reference to the underlying opaque values should not be needed.

While we don't _need_ references, they definitely don't hurt, and guarantee that we don't let undefined behavior slip outside of the remaining `unsafe` blocks. They can be trivially coerced to pointers without casting as well, so if `self.module` is `NonNull<LLVMModule>`, you can pass it to functions that accept `LLVMModuleRef` as an argument via `self.module.as_mut()`. 

> So I see no benefit of using NonNull\<T>.

It guarantees that we are not able to get multiple mutable references, or a mutable reference from an immutable context unless we explicitly cast it. Then we don't need to carefully audit where we accidently passed a mutable pointer into an extern function or dereferenced the mutable pointer from an immutable context.

> I think the real discussion is which methods should take &mut self and which just &self to better reflect the underlying mutations.

I agree, but what I'm proposing is in essence inverting the default to err on the safe side. Instead of looking where we _need_ to make the method take `&mut self` to guarantee safe behavior (this also affects the optimizations the compiler is allowed to do), we ask the compiler to always require it unless we prove otherwise (and do an explicit cast)

**Comment by TheDan64** [comment]
I don't believe inkwell's pattern here is unsound because it's more similar to that of interior mutability.

Your examples don't totally make sense I think. For example in `context_add_module` you have:
```rust
        let context = &mut *context.0;
        ModuleRef(context.add_module())
```
but C++ can't do this as it doesn't have Rust references.

**Comment by leifhelm** [comment]
@pablosichert your suggestion would essentially block users from creating two modules in one context at the same time. I can see that this is the desired behavior as mutating one module could affect all other modules in the same context.
`Module` should definitely be `Drop`:
https://llvm.org/doxygen/group__LLVMCCoreModule.html#ga6bf4a0a387cf7fe04cbe0438cdb36a51

**Comment by pablosichert** [comment]
> I don't believe inkwell's pattern here is unsound on the whole because it's more similar to that of interior mutability. 

While it's possible that LLVM correctly adopts interior mutability without invalidating any references or causing other undefined behavior, personally I would not make that assumption and would also not expose this in the public Rust API. What is the reason to expose interior mutability in the first place, would you expose the same API if you were to implement a builder in Rust from scratch?

At least personally I was surprised/confused to see the many methods in inkwell that are clearly mutating internal state take `&self`, and I can't say that I perceived that as convenient.

When you use interior mutability in Rust, at least you get panics when violating invariants unless you use the `unsafe` APIs, which can not be said for C++/LLVM. So if it can't guard us from that, I'd at least like to place assertions that allow safe usage in the _safe_ Rust wrapper. I'm arguing from a point of view where any segfault is unacceptable when I embed this into my application.

> Your examples don't totally make sense I think [...]

Of course this is not a sensible way to implement a C API, it was just to illustrate one of the many things that can go wrong. I'm merely saying it is _possible_ that parts of the C++ is implemented like this and exposed to the C API, even if inadvertently. This is not a point about the actual implementation of LLVM, and my example wasn't meant to mirror that.

> but C++ can't do this as it doesn't have Rust references.

You can cast pointers to references in C++ via `&*`, so you can implement the exact same pattern in C++. Or I might be missunderstanding your argument?

**Comment by pablosichert** [comment]
> your suggestion would essentially block users from creating two modules in one context at the same time

I can see how this is problem when you want to merge modules or extract information from one module while building the other one. It would not stop you from first implementing one module, and then the second module in the same context, but I agree that it's possible that this is not be good enough.

> Module should definitely be `Drop`

Yes, but I'm also not arguing against that anywhere. I was suggesting the context should own them and drop them when the context is cleaned up. If you're referring to the toy example I made, `Module` has `Drop`. It's just not implemented explicitly

**Comment by pablosichert** [comment]
Related issues that I caught while browsing through the code:

https://github.com/TheDan64/inkwell/blob/14720da487fa5dd8640f538408d260b6a41a106c/src/module.rs#L432

This takes a shared `&self` reference to `Module`. However, in LLVM [`EngineBuilder::EngineBuilder`](https://llvm.org/doxygen/classllvm_1_1EngineBuilder.html#a942eae70b5e6253100a4aa1ad843128a) takes a `unique_ptr<Module>`. This is even acknowledge in the code, but ignored:

https://github.com/TheDan64/inkwell/blob/14720da487fa5dd8640f538408d260b6a41a106c/src/module.rs#L448-L449

Similar case in `ExecutionEngine`, where it takes a shared reference to `Module`

https://github.com/TheDan64/inkwell/blob/20614c6499be0d911f68855917e1e6e11a3392d7/src/execution_engine.rs#L198

but in LLVM [`ExecutionEngine::addModule`](https://llvm.org/doxygen/classllvm_1_1ExecutionEngine.html#a628a513b3b717f80fdc8e937cc503f26) takes `unique_ptr<Module>`.

In the C bindings, LLVM [casts](https://github.com/llvm/llvm-project/blob/abc17a67519747be36f1fd03e227c5103da4c677/llvm/lib/ExecutionEngine/ExecutionEngineBindings.cpp#L256-L258) the provided pointers from the C reference to `unique_ptr<Module>`.

In both cases the module should be moved and `std::mem::forget` instead

**Comment by pablosichert** [comment]
Some observations about how LLVM is used in the Rust compiler:

---

Like inkwell, they tie together the lifetime of a context and module, and don't assume exclusive ownership for a module of the context:

https://github.com/rust-lang/rust/blob/1158ade996d69498e946ca5901184aaa3e0edf4c/compiler/rustc_codegen_llvm/src/context.rs#L49-L50
```rust
pub struct CodegenCx<'ll, 'tcx> {
    ...
    pub llmod: &'ll llvm::Module,
    pub llcx: &'ll llvm::Context,
    ...
 }
 ```
 
 ---
 
 They also don't require a mutable reference of the context to create a module:
 
https://github.com/rust-lang/rust/blob/1158ade996d69498e946ca5901184aaa3e0edf4c/compiler/rustc_codegen_llvm/src/context.rs#L135-L142
 
 ```rust
 pub unsafe fn create_module<'ll>(
    tcx: TyCtxt<'_>,
    llcx: &'ll llvm::Context,
    mod_name: &str,
) -> &'ll llvm::Module {
    let sess = tcx.sess;
    let mod_name = SmallCStr::new(mod_name);
    let llmod = llvm::LLVMModuleCreateWithNameInContext(mod_name.as_ptr(), llcx);
    ...
 }
 ```
 
 ---
 
 They do however propagate that information into the builder:
 
https://github.com/rust-lang/rust/blob/1158ade996d69498e946ca5901184aaa3e0edf4c/compiler/rustc_codegen_llvm/src/builder.rs#L35-L38
 
 ```rust
 pub struct Builder<'a, 'll, 'tcx> {
    pub llbuilder: &'ll mut llvm::Builder<'ll>,
    pub cx: &'a CodegenCx<'ll, 'tcx>,
}
```

---

And require a mutable reference to the builder, and tie the values to the lifetime of the context:

https://github.com/rust-lang/rust/blob/1158ade996d69498e946ca5901184aaa3e0edf4c/compiler/rustc_codegen_llvm/src/builder.rs#L174-L1185

```rust
fn fadd_fast(&mut self, lhs: &'ll Value, rhs: &'ll Value) -> &'ll Value {
    unsafe {
        let instr = llvm::LLVMBuildFAdd(self.llbuilder, lhs, rhs, UNNAMED);
        llvm::LLVMRustSetFastMath(instr);
        instr
    }
}
```

**Comment by TheDan64** [comment]
> While it's possible that LLVM correctly adopts interior mutability without invalidating any references or causing other undefined behavior, personally I would not make that assumption and would also not expose this in the public Rust API.

We don't just "make that assumption", we have an extensive test suite that shows this. If someone can use inkwell to prove otherwise, I'd be happy to review it. That's a bug either in inkwell or LLVM.

> What is the reason to expose interior mutability in the first place, would you expose the same API if you were to implement a builder in Rust from scratch?

The reason being that there's no reason not to. The question of what I would do if I was writing this in Rust is irrelevant, because we're not creating from scratch, we're applying a layer ontop of existing code. And if it really is safely mutable interiorly, then making everything take exclusive references would unnecessarily burden the API in most cases.

> At least personally I was surprised/confused to see the many methods in inkwell that are clearly mutating internal state take &self, and I can't say that I perceived that as convenient.

I suspect this is a misunderstanding of `&mut` vs `&`. Although typically called `mutable` vs `immutable` references, this is sort of a misnomer. Yes, that's what they give you in many default cases, but their true functionality succeeds that. Better terms for them are `exclusive access` vs `shared access` references. Because with the latter you can mutate via internal mutability and that isn't inherently incorrect and in many cases is desired. And you are correct that there are guards in place to make that happen. Inkwell relies on both LLVM's guards and also insert our own (such as with lifetimes, but also runtime or compile time checks where we've found UB to be possible).

> Of course this is not a sensible way to implement a C API, it was just to illustrate one of the many things that can go wrong. I'm merely saying it is possible that parts of the C++ is implemented like this and exposed to the C API, even if inadvertently. This is not a point about the actual implementation of LLVM, and my example wasn't meant to mirror that.

Ok fair, but the actual implementation of LLVM *is* important here. Both I and other contributors have spent countless hours reviewing LLVM source code to verify the actual implementation. Not to imply that inkwell is perfectly sound, but just to say that it has been battled tested statically, dynamically, and in production.

> You can cast pointers to references in C++ via &*, so you can implement the exact same pattern in C++. Or I might be missunderstanding your argument?

You can't implement the exact same pattern though. C++ references are very different than Rust references, they only guarantee that the pointer is non-null, not that it is valid or exclusive.

**Comment by TheDan64** [comment]
> This takes a shared &self reference to Module. However, in LLVM [EngineBuilder::EngineBuilder](https://llvm.org/doxygen/classllvm_1_1EngineBuilder.html#a942eae70b5e6253100a4aa1ad843128a) takes a unique_ptr<Module>. This is even acknowledge in the code, but ignored:

It isn't ignored though, this is handled by the assignment to `self.owned_by_ee` a little later. ExecutionEngines have very complex lifetimes, so we ended up using reference counting for them.

**Comment by pablosichert** [comment]
I recognize there's a discrepancy between how I would ideally model and approach this problem, and what actually exists and is implemented. We just seem to disagree on the relevance of the latter. I would wrap an existing API the same way I would design it in Rust to sidestep issues like this. That's my opinion of course, and I can see that this might not be the most practical tradeoff.

I can only observe that I'm irritated by a workflow that looks like this: I run into a segfault, go back to inkwell and recognize that by the patterns it uses, the error surface is practically all of inkwell and LLVM. Which is precisely what I wanted to avoid when deciding to use Rust.

> If someone can use inkwell to prove otherwise, I'd be happy to review it. That's a bug either in inkwell or LLVM. [...] The reason being that there's no reason not to.

The reasoning would be that this class of bugs would not exist, and nothing needs to be proven. The problem is exactly that even with an extensive test suite you can't rule out the absence of bugs that only occur when very specific conditions are met while holding multiple references.

I acknowledge however, after your arguments and reviewing the LLVM source code, that regarding the `Context`/`Module` this pattern should be fine in its current implementation.

You're also right about the exclusive vs. shared access, just that personally I would decide against using interior mutability where possible both because of runtime-checks that are needed to make this safe and possibly unexpected behavior.

> You can't implement the exact same pattern though. C++ references are very different than Rust references, they only guarantee that the pointer is non-null, not that it is valid or exclusive.

You could, just that it's a terrible idea since it lacks these guarantees. So I agree that this specific example is contrived and in practice should not be exposed like that on the top level of the API.

I'm going to close this issue since you seem intentional about this design, and I agree that there should be nothing inherently wrong with it. While acknowleding that in this case safety depends on very specific implementation details.

(Doesn't mean that I'm closing this discussion, feel free to continue in this thread.)

**Comment by pablosichert** [comment]
> this is handled by the assignment to `self.owned_by_ee` a little later as well as the check to `self.owned_by_ee` a little earlier

Good point, I missed that when reviewing. However, shouldn't that mean that every other method should check for this? E.g. what stops you from creating a module, creating an execution engine for it and JITting it (which should destroy the module). And then afterwards print the module to a string:

https://github.com/TheDan64/inkwell/blob/14720da487fa5dd8640f538408d260b6a41a106c/src/module.rs#L781-L785

I think I tried that and it still worked, but the fact that it does is entirely undefined behavior

**Comment by TheDan64** [comment]
> I can only observe that I'm irritated by a workflow that looks like this: I run into a segfault [...]

If you run into segfaults please open an issue with reproducible steps so that we can look into it. It's unlikely to be a systemic problem with inkwell but rather an edge case that needs to be handled or accounted for. Or a problem in LLVM itself that we can't do much about

> Which is precisely what I wanted to avoid when deciding to use Rust.

I get that, but the problem isn't unique to inkwell or its approach, this is the kind of thing you run into with any crate that wraps a non trivial C/++ library. There will always be edge cases because the C/++ code does something wild that you wouldn't do in Rust.

> The reasoning would be that this class of bugs would not exist, and nothing needs to be proven.

I disagree, just using mutable references everywhere wouldn't magically solve the problem. LLVM will follow pointers like crazy and mutate objects that you don't even expect to be mutated behind the scenes.

> [...] even with an extensive test suite you can't rule out the absence of bugs that only occur when very specific conditions are met while holding multiple references.

I do agree with this, tests don't prove the absence of bugs. However, the solution is to open an issue when you encounter such a problem so that we can fix and improve the crate. Also, the fact that most LLVM types are not thread safe and therefore not `Send` / `Sync` in inkwell, helps a lot to maintain this invariant because accesses are well ordered in a single thread.

> Good point, I missed that when reviewing. However, shouldn't that mean that every other method should check for this?

hmm, I don't think so because it keeps a ref counted copy of the EE alive. But maybe you're onto something, would have to look into it again. EEs are definitely some of the most complex parts of inkwell. Would not be surprised to find an edge case there
