### ISSUE TITLE
could not find native static library `Polly` on linux

### ISSUE THREAD

**Issue by Lioncat2002** [TheDan64/inkwell#336]
**Describe the Bug**
Trying to install the inkwell package on linux gives the error:
```
   Compiling llvm-sys v130.0.4
   Compiling inkwell v0.1.0 (https://github.com/TheDan64/inkwell?branch=master#25b9fc58)
error: could not find native static library `Polly`, perhaps an -L flag is missing?

error: could not compile `llvm-sys` due to previous error
warning: build failed, waiting for other jobs to finish...
```

**To Reproduce**
Trying to install inkwell with llvm version 13.0.1

**Expected Behavior**
There should be a build success

**LLVM Version (please complete the following information):**
 - LLVM Version: 13.0.1
 - Inkwell Branch Used: llvm-13.0

**Desktop (please complete the following information):**
 - OS: Kali Linux(should be similar to Ubuntu 18)

**Comment by Lioncat2002** [comment]
Issue fixed,
installed llvm version 12 but works now

**Comment by thinkrapido** [comment]
How did you fix this?
For me installing v12 is not working!

**Comment by thinkrapido** [comment]
I have ubuntu 22.04

**Comment by thinkrapido** [comment]
needed to install clang as well

**Comment by thinkrapido** [comment]
solved

**Comment by dannywillems** [comment]
I confirm installing clang fixes the problem.
You can see `libLLVMPolly.a` is missing in `/usr/lib/llvm-12/lib` (`ls /usr/lib/llvm-12/lib | grep Polly`). The dynamic library file `LLVMPolly.so` is present but not the static one (`libLLVMPolly.a`).
You can fix the problem by using the command:
```
sudo apt-get install llvm-12-dev llvm-12-tools clang-12
```
Running again `ls /usr/lib/llvm-12/lib | grep Polly` should give the output:
```
libPolly.a
libPollyISL.a
libPollyPPCG.a
LLVMPolly.so
```
I hope it will help other people to debug.

**Comment by pedrodesu** [comment]
I can't seem to make this work. I'm using llvm 16, and I keep getting this same error. I have `clang-16`, `llvm-16-dev` and `llvm-16-tools` installed.
Running `ls /usr/lib/llvm-16/lib | grep Polly` returns only `LLVMPolly.so`, so I'm guessing the problem's there.
I'd really appreciate some help.

**Comment by pedrodesu** [comment]
Just found the culprit: It had to do with the source, the aforementioned llvm.sh script isn't very reliable. In the same website, retrieving the llvm signature and installing the key packages manually works.

**Comment by Agnishom** [comment]
Which key packages did you install @pedrodesu ?

**Comment by mrbluecoat** [comment]
`libpolly-18-dev` on newer versions of Ubuntu
