### ISSUE TITLE
The given type is not a basic type. in function llvm.dbg.declare

### ISSUE THREAD

**Issue by subtil-next** [TheDan64/inkwell#340]
**Describe the Bug**
Encountering `The given type is not a basic type.` When attempting to decode params of the function `llvm.dbg.declare` 

**To Reproduce**
Consider the following:

```c

int square(int num) {
    return num * num;
}

int main() {
    int x = 2;
    x = square(x)+4;
    return x;
}
```

compiled with:

```
Apple clang version 13.1.6 (clang-1316.0.21.2.5)
```

```
clang -O0 -g -c -emit-llvm foo.c -o foo.bc
```

Test application (compiled against feature `llvm13-0`)

```rust
let path = Path::new("clang_test/foo.bc");
let context = Context::create();
let module = Module::parse_bitcode_from_path(&path, &context).expect("Failed to parse module");

let some_function = module.get_function("llvm.dbg.declare").unwrap();

let mut str: String = "".to_owned();
for param in some_function.get_params() {
    str += &format!(", {:#?}", param);
}
info!("Params: {}", str);
```

**Expected Behavior**
Expected non crash against get_params. 

**LLVM Version (please complete the following information):**
 - LLVM Version: 13
 - Inkwell Branch Used: main

**Desktop (please complete the following information):**
 - OS: OSX 12.5 

**Additional Context**

I am reading through the documentation about what the values should be in this case. but the .ll looks like this:

```
; Function Attrs: noinline nounwind optnone ssp uwtable
define i32 @square(i32 %0) #0 !dbg !15 {
  %2 = alloca i32, align 4
  store i32 %0, i32* %2, align 4
  call void @llvm.dbg.declare(metadata i32* %2, metadata !19, metadata !DIExpression()), !dbg !20
  %3 = load i32, i32* %2, align 4, !dbg !21
  %4 = load i32, i32* %2, align 4, !dbg !22
  %5 = mul nsw i32 %3, %4, !dbg !23
  ret i32 %5, !dbg !24
}

; Function Attrs: nofree nosync nounwind readnone speculatable willreturn
declare void @llvm.dbg.declare(metadata, metadata, metadata) #1
```

**Comment by TheDan64** [comment]
hmm, what exactly are the usecase for metadata params?

**Comment by subtil-next** [comment]
the `llvm.dbg.declare` metadata is included with the `-g` command line switch. 

I am trying to do static analysis, I would like to be able to tie issues back to original source code in order to help speed up the remediation of anything found.  the `-g` command line switch incudes the `!dbg !20` information such as `!20 = !DILocation(line: 2, column: 16, scope: !18)`.

So the specific use case is not tied to this function, but this function is a byproduct of the use case and causing issues during analysis. 

I had originally hoped that this would be a simple fix, but it appears to be a little more complicated.

**Comment by subtil-next** [comment]
so did some more digging.

```
declare void @llvm.dbg.declare(metadata, metadata, metadata) #1
```

the parameters don't actually contain any metadata. So when parsing functions, this one should be skipped. 

Sorry to bother you with this.
