### ISSUE TITLE
Add support for array and pointer types in debug_info

### ISSUE THREAD

**Issue by ghaith** [TheDan64/inkwell#348]
**Is your feature request related to a problem? Please describe.**
The functions [LLVMDIBuilderCreatePointerType](https://docs.rs/llvm-sys/140.0.2/llvm_sys/debuginfo/fn.LLVMDIBuilderCreatePointerType.html) and [LLVMDIBuilderCreateArrayType](https://docs.rs/llvm-sys/140.0.2/llvm_sys/debuginfo/fn.LLVMDIBuilderCreateArrayType.html) are not implemented in inkwell, they are needed to create debug information for arrays and pointers.

**Describe the solution you'd like**
Extend the debug_info.rs to support creating the new type

I can provide a PR soon to add support for this.

**Comment by TheDan64** [comment]
Sure, sounds good!
