### ISSUE TITLE
'expected enum `LLVMBasicBlock`, found enum `llvm_sys::LLVMBasicBlock`' when trying to pass LLVMBasicBlockRef to external C function

### ISSUE THREAD

**Issue by muke101** [TheDan64/inkwell#350]
**Describe the Bug**
I'm trying to pass an LLVMBasicBlockRef retrieved through `.get_ref()` with the internal-getters feature enabled to an external C function defined in Rust as the following:

`
use llvm_sys::prelude::LLVMBasicBlockRef;

extern "C" { fn foo(block: LLVMBasicBlockRef) }
`

When I pass the result of a call to `get_ref()` on a `BasicBlock` value to this function, rustc gives the error:
`
error[E0308]: mismatched types
  --> src/main.rs:52:54
   |
52 |             let mut inst_value_ref = get_first_inst_value_ref(block.get_ref());
   |                                                               ^^^^^^^^^^^^^^^ expected enum `LLVMBasicBlock`, found enum `llvm_sys::LLVMBasicBlock`
   |
   = note: expected raw pointer `*mut LLVMBasicBlock`
              found raw pointer `*mut llvm_sys::LLVMBasicBlock`
   = note: perhaps two different versions of crate `llvm_sys` are being used?
`

It seems, as rustc suggests, two llvm_sys versions are in use - one that I'm importing in my own code and then one that inkwell uses internally, giving inconsistent enum values. 

**LLVM Version (please complete the following information):**
 - LLVM Version: 14
 - Inkwell Branch Used: llvm14-0
 - llvm-sys crate version: 120

**Desktop (please complete the following information):**
 - OS: Gentoo stable

**Comment by TheDan64** [comment]
Yes, you can't use a different llvm version from the one inkwell is using. This is out of inkwell's hands

**Comment by muke101** [comment]
Ah, I didn't realise llvm-sys's versions worked like that, this fixed it. Thanks.
