### ISSUE TITLE
ContextRef in debug builder

### ISSUE THREAD

**Issue by ghaith** [TheDan64/inkwell#355]
**Describe the Bug**
I saw a problem when using the `DIGlobalVariableExpression::as_metadata_value` which still uses context, meaning I cannot just pass the context ref the module holds.
I assume the references to context can all be changed to ContextRef, but it might still break some code until this is done. 

If ContextRef is meant to be a reference to the Context that the module holds, it might be meaningful for it to implement Deref as well.

**Comment by TheDan64** [comment]
ContextRef can't deref to Context or vice versa, since it doesn't actually use one. Will have to think about this some more

**Comment by TheDan64** [comment]
Been thinking about this and the only approach I've really got is a new context trait that is implemented for both Context and ContextRef

**Comment by TheDan64** [comment]
Either that or like `AsRef<PrivateContextType>`

**Comment by TheDan64** [comment]
Working on a fix for this. Going with the first approach
