### ISSUE TITLE
FunctionValue to PointerValue

### ISSUE THREAD

**Issue by JCBurnside** [TheDan64/inkwell#356]
**Is your feature request related to a problem? Please describe.**
Allow for a function pointer to be easily gotten.  Atm have to go a long way to get the pointer value by first building a bit cast and then storing that result in a pointer.

**Describe the solution you'd like**
either as a part of `FunctionValue` or `Builder::build_store<T>(PointerValue,T)`.  should generate the following ir `store ptr @function, ptr %pointer, align 8, !dbg !22`

**Describe possible drawbacks to your solution**
can't think of any atm.

**Describe alternatives you've considered**
bitcast then store.

**Additional context**
code used to get the store instruction https://gcc.godbolt.org/z/jaM4oqqv3

**Comment by JCBurnside** [comment]
UPDATE build bit cast has the same issue.  how are we meant to get function pointers?

**Comment by TheDan64** [comment]
You actually can do this already `fn_value.as_global_value().as_pointer_value()`

**Comment by TheDan64** [comment]
Closing as there's a way to do this already. If you want to add and doc a convenience method on FnValue then I'd be open to that
