### ISSUE TITLE
No pointer compares.

### ISSUE THREAD

**Issue by JCBurnside** [TheDan64/inkwell#358]
**Is your feature request related to a problem? Please describe.**
I would have to convert `PointerValue`s to `IntValue`s to do a compare.

**Describe the solution you'd like**
have a function on `Builder` to have it generate raw pointer compare instructions ie 
```llvm
  %8 = load i8*, i8** %3, align 8, !dbg !28
  %9 = load %struct.Str*, %struct.Str** %2, align 8, !dbg !29
  %10 = getelementptr inbounds %struct.Str, %struct.Str* %9, i32 0, i32 1, !dbg !30
  %11 = load i8*, i8** %10, align 8, !dbg !30
  %12 = icmp ne i8* %8, %11, !dbg !31
```

**Describe possible drawbacks to your solution**
might not work on older versions of llvm but could make it generate the converting to ints first then doing the compare.

**Describe alternatives you've considered**
converting to `IntValue`s first.

**Additional context**
C code to generate the llvm ir [here](https://gcc.godbolt.org/z/6qorKTTbq)

**Comment by JCBurnside** [comment]
simplified for ease of reading here is a better example of a ptr compare.  no need to convert to ints 
https://gcc.godbolt.org/z/rd3xMq6oG

**Comment by TheDan64** [comment]
Are there LLVM C API functions we're missing for this? If so we can certainly add them. Otherwise there's not much we can do

**Comment by JCBurnside** [comment]
given that it generates the same same instruction as an int compare why can't we use the same?

**Comment by TheDan64** [comment]
@JCBurnside do you think you'd be able to verify all the comparisons that are valid on pointers? For example, are more esoteric compares like AtomicCmpXchg still valid on them?

**Comment by JCBurnside** [comment]
Isn't `AtomicCmpXchg` a separate instructions from `icmp` and not really relevant here? as far as I am aware (and I even asked someone i know who contributes to LLVM) so long as the pointer types match it should be valid for any icmp. and from the api I am seeing that was a different function entirely anyway?
