### ISSUE TITLE
LLVM 15 support

### ISSUE THREAD

**Issue by hedgar2017** [TheDan64/inkwell#359]
Hey guys, do you plan to add the LLVM 15 support in the near future?
We plan to update our project to it so we may offer some help if needed.

**Comment by TheDan64** [comment]
I don't believe anyone's started work on it, so feel free

**Comment by hardcoresummer** [comment]
To deal with Opaque pointer support in LLVM 15, should we add in each Pointer-related Value struct the corresponding type? Or the library user has to store the type somewhere else?

**Comment by thangvip4321** [comment]
It's here: https://llvm.org/docs/OpaquePointers.html

**Comment by TheDan64** [comment]
As far as I can tell it doesn't seem to really affect any existing code? There's just a new method to set the pointer mode? https://docs.rs/llvm-sys/latest/llvm_sys/core/fn.LLVMContextSetOpaquePointers.html

**Comment by aditya-solana** [comment]
Can we add llvm-15 in the Cargo.toml file at least. My installation is failing because Fedora37 does not have llvm-14 by default. llvm-sys has added support for llvm-15.

**Comment by TheDan64** [comment]
Unfortunately it's not as simple as just adding it to the Cargo.toml, a bunch of code paths have to be updated. I would do it but I don't have access to llvm15 atm

**Comment by TheDan64** [comment]
Happy to review someone's PR

**Comment by aditya-solana** [comment]
Are there instructions to use a specific version of llvm? When I download inkwell and build from source using `cargo build` this is the first error I'm getting:

```sh
  Compiling inkwell v0.1.0 (/run/media/adityak/tb_half/inkwell)
error: One of the LLVM feature flags must be provided: llvm4-0 llvm5-0 llvm6-0 llvm7-0 llvm8-0 llvm9-0 llvm10-0 llvm11-0 llvm12-0 llvm13-0 llvm14-0 
   --> src/lib.rs:95:9
    |
95  |         compile_error!(concat!("One of the LLVM feature flags must be provided: ", $($all, " "),*));
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
106 | assert_unique_used_features! {"llvm4-0", "llvm5-0", "llvm6-0", "llvm7-0", "llvm8-0", "llvm9-0", "llvm10-0", "llvm11-0", "llvm12-0", "llvm13-0", "llvm14-0"}
    | ----------------------------------------------------------------------------------------------------------------------------------------------------------- in this macro invocation
    |
    = note: this error originates in the macro `assert_used_features` which comes from the expansion of the macro `assert_unique_used_features` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: use of undeclared crate or module `llvm_sys`
 --> src/support/error_handling.rs:4:5
  |
4 | use llvm_sys::core::{LLVMGetDiagInfoDescription, LLVMGetDiagInfoSeverity};
  |     ^^^^^^^^ use of undeclared crate or module `llvm_sys`
```

**Comment by aditya-solana** [comment]
Side note: even llvm-sys doesn't build on Fedora 37: https://gitlab.com/taricorp/llvm-sys.rs/-/issues/40

**Comment by aditya-solana** [comment]
> opaque pointers

For now we can get around opaque pointer changes by enforcing the old behavior:
https://llvm.org/docs/OpaquePointers.html#transition-state, the migration to opaque pointers can be done in stages if that is more reasonable.
