### ISSUE TITLE
[debug] debug location persists even after builder position changed

### ISSUE THREAD

**Issue by Chronostasys** [TheDan64/inkwell#360]
**Describe the Bug**
After setting a debug location to builder, it cannot be removed. Even after calling `position_at_end`.  

**To Reproduce**
- call set_current_debug_location
- call position_at_end, point builder to another block
- add instructions
- gennerate ir

**Expected Behavior**
The debug location get automatically removed from builder after call `position_at_end`

**LLVM Version (please complete the following information):**
 - LLVM Version: 14
 - Inkwell Branch Used: master

**Desktop (please complete the following information):**
 - OS: macOS Monterey

**Additional Context**
Many compilers may generate additional instructions wich cannot be mapped to source files, so providing a way to manually remove debug location should be considered.

**Comment by TheDan64** [comment]
Does the LLVM C API provide a way to do this? Otherwise there is nothing we can do

**Comment by Chronostasys** [comment]
I found an api on builder `unset_current_debug_location` which seems to resolve this issue. Thanks!
