### ISSUE TITLE
Bind inkwell's major version to llvm version

### ISSUE THREAD

**Issue by gavrilikhin-d** [TheDan64/inkwell#376]
**Is your feature request related to a problem? Please describe.**
Features are not meant to solve versioning problem, even rust docs say so. The problems is that cargo doesn't support exclusive features and looks like won't support them any time soon. This leads to manual management of exclusiveness inside of inkwell.

**Describe the solution you'd like**
Using major version to specify llvm version, minor and patch stays related to inkwell itself. Remove features for llvm versions.

**Describe possible drawbacks to your solution**
Need to back-port changes across different versions. Don't know if can share code across different versions of inkwell

**Comment by gavrilikhin-d** [comment]
I purpose that inkwell `14.x.y` always uses `llvm14` and so on

**Comment by gavrilikhin-d** [comment]
Is it possible to maintain 3+ versions of rust library without code duplication?

**Comment by TheDan64** [comment]
What you are proposing would be too much of a maintenance burden. The rust docs suggesting that features should always be additive is a guidelines, not a strict rule that must always be adhered to in every circumstance

**Comment by TheDan64** [comment]
A crucial part of software engineering is not just knowing the rules - but also knowing when to break them.

**Comment by gavrilikhin-d** [comment]
Inkwell can use git branches to maintain multiple versions without code duplication

**Comment by gavrilikhin-d** [comment]
This will literally eradicate all checks for llvm versions from code and will simplify api

**Comment by TheDan64** [comment]
We use to do this with got branches and it's very exhausting to make sure the branches stay in sync. When someone makes a change, it needs to be made against all 12 branches

**Comment by gavrilikhin-d** [comment]
Got it, thanks
