### ISSUE TITLE
Add `fn_type` to enums

### ISSUE THREAD

**Issue by gavrilikhin-d** [TheDan64/inkwell#380]
**Is your feature request related to a problem? Please describe.**

My compilers dynamically lower types to inkwell's:
```rs
pub fn lower_type(&self, ty: &mir::Type) -> inkwell::types::BasicTypeEnum;
``

Later, it create function with such lowered return type
```rs
self.lower_type(ty).fn_type(params, false) // Not implemented
```
This most obvious approach doesn't work.

**Describe the solution you'd like**
I'd like `BasicTypeEnum`, `BasicMetadataTypeEnum`, `AnyTypeEnum` to implement:
```rs
pub fn fn_type(self, param_types: &[BasicMetadataTypeEnum<'ctx>], is_var_args: bool) -> FunctionType<'ctx>
```
Types from `BasicTypeEnum` may always be used as return type, yet I'm not sure about `MetadataType` and `FunctionType`.

Probably, `BasicMetadataTypeEnum` and `AnyTypeEnum` must change signature to:
```rs
pub fn fn_type(self, param_types: &[BasicMetadataTypeEnum<'ctx>], is_var_args: bool) -> Result<FunctionType<'ctx>, ()>
```

**Comment by endorpersand** [comment]
`BasicTypeEnum` *does* have a fn_type method. However, it's implemented as a part of `BasicType`, so to use `BasicTypeEnum`'s fn_type method you need to import `BasicType` in your module.

As for `MetadataType` and `FunctionType`, the [LLVM language reference](https://llvm.org/docs/LangRef.html#function-type) seems to read that only `void` and first-class types are permitted, which excludes `MetadataType` and `FunctionType`.
