### ISSUE TITLE
Opaque pointers

### ISSUE THREAD

**Issue by gavrilikhin-d** [TheDan64/inkwell#382]
**Is your feature request related to a problem? Please describe.**
LLVM is moving towards opaque pointers. In LLVM 16 non-opaque pointers are forbidden. It's probably worth to start implementing optional support for them now.

**Describe the solution you'd like**
Add new type `OpaquePointerType`

**Describe possible drawbacks to your solution**
None, except more work. Opaque pointers are inevitable

**Describe alternatives you've considered**
Add `Context::use_opaque_pointers` function, as LLVM did.

**Comment by TheDan64** [comment]
I believe this is covered by https://github.com/TheDan64/inkwell/pull/383?
