### ISSUE TITLE
`Context::const_string` returns incorrect type

### ISSUE THREAD

**Issue by endorpersand** [TheDan64/inkwell#390]
**Describe the Bug**
`Context::const_string` returns a `VectorValue`, when it is supposed to return an `ArrayValue`.

**To Reproduce**
The example in the docs clearly shows that the function does not return a `VectorValue`:
```rs
use inkwell::context::Context;
use inkwell::values::AnyValue;

let context = Context::create();
let string = context.const_string(b"my_string", false);

assert_eq!(string.print_to_string().to_string(), "[9 x i8] c\"my_string\"");
```

**Expected Behavior**
`Context::const_string` should return an `ArrayValue`.

**LLVM Version (please complete the following information):**
 - LLVM Version: 14.0.6
 - Inkwell Branch Used: llvm14-0

**Desktop (please complete the following information):**
 - OS: macOS 13.0.1

**Comment by TheDan64** [comment]
Good catch, would you like to file a PR?
