### ISSUE TITLE
Expose GlobalAlias and GlobalIFunc types

### ISSUE THREAD

**Issue by DCNick3** [TheDan64/inkwell#411]
**Is your feature request related to a problem? Please describe.**

I want to port llvm's [`SplitModule`](https://llvm.org/doxygen/SplitModule_8cpp_source.html) function to inkwell (this function is not exposed through LLVM C API). It does some low-level operations on modules, including special handling for aliases and ifuncs.

Unfortunately, it doesn't seem possible to fully implement it with inkwell, as the APIs for getting the aliases/ifuncs of the module are simply omitted. I can't even detect that they are even there and error out...

AFAIU, they were not included in inkwell because they are quite obscure and not that useful? (I have huge trouble finding any docs about them). Still kind of sad that I can't even observe them.

**Describe the solution you'd like**
Ideally - a fully exposed API surface.

Or at least a way to tell that a module has any ifuncs or alises so that I can error out and not fail silently.

**Describe possible drawbacks to your solution**
The former - obviously a lot of work that is quite niche.

The latter - not much I think?

**Describe alternatives you've considered**
Just ignore the problem ~~and hope it goes away~~ :see_no_evil:
I just don't like how the lack of even possibility to observe the existence of aliases/ifuncs can silently introduce problems

**Comment by DCNick3** [comment]
After looking at it a bit deeper, it isn't really feasible to port the `SplitModule`, as it uses a lot of low-level LLVM functions that are not exposed by inkwell/C API.

It would be much simpler to rewrite the frontend to do the split as it generates the code.

One other way would to work with LLVM folks to get the SplitModule exposed in C API...

*sigh*

**Comment by benpye** [comment]
I think it would still be useful to have `GlobalAlias` exposed at least. I am looking to have something similar to the symbol rewriter pass in LLVM ( https://github.com/llvm/llvm-project/blob/main/llvm/lib/Transforms/Utils/SymbolRewriter.cpp ) because expressing my transformations with regex is getting quite unwieldy.
