### ISSUE TITLE
`build_load` confuses rust-analyzer

### ISSUE THREAD

**Issue by willtunnels** [TheDan64/inkwell#414]
Inkwell decided to have different parameters to `build_load` under different (mutually exclusive) feature sets. This confuses rust-analyzer and causes it to mark all calls to `build_load` under `llvm15-0` and higher as errors (mismatched-arg-count). This is pretty annoying. I'm not sure if this pattern shows up elsewhere in Inkwell.

Mutually exclusive features are always a messy hack, but perhaps we can alleviate this annoyance. One possibility would be to name `build_load` something different under `llvm15-0` and higher.

EDIT: I now see that this design pattern occurs several places.

**Comment by TheDan64** [comment]
RA allows you to specify feature flags btw, so it should be able to see the correct version if you specify

**Comment by willtunnels** [comment]
I tried setting `rust-analyzer.cargo.features` to `inkwell/llvm15-0`, but that didn't fix the problem. Did you have a different setting in mind? You're right that this might be an RA issue.

**Comment by TheDan64** [comment]
Yeah, that's what I was thinking of

**Comment by TheDan64** [comment]
Closing as likely not an inkwell issue
