### ISSUE TITLE
Unable to Access Context Dynamically in LLVMManager: Seeking Alternative Approach

### ISSUE THREAD

**Issue by Daniel-Boll** [TheDan64/inkwell#423]
**Is your feature request related to a problem?**

I encountered a problem while trying to structure my code to create a specific API for managing LLVM functions. The issue is that I couldn't find a way to make the **`singleton_manager`** work with the **`Context`** because the **`singleton_manager`** requires a static lifetime, but I need access to the **`Context`** dynamically.

<details>
  <summary>PrintfExtern snippet example</summary>

```rust
use crate::codegen::llvm::manager::LLVMManager;

pub struct PrintfExtern;

impl PrintfExtern {
  pub fn declare() {
    let manager = LLVMManager::get();
    let module = manager.module();

    let printf_type = manager
      .i32_type()
      .fn_type(&[manager.ptr_i32_type().into()], true);
    module.add_function("printf", printf_type, None);
  }

  pub fn get() -> inkwell::values::FunctionValue<'static> {
    let manager = LLVMManager::get();
    let module = manager.module();

    module.get_function("printf").unwrap_or_else(|| {
      PrintfExtern::declare();
      module
        .get_function("printf")
        .expect("printf function not found")
    })
  }

  pub fn call_from_str(message: &str) {}

  pub fn call(args: &[inkwell::values::BasicMetadataValueEnum]) {
    let manager = LLVMManager::get();

    manager
      .builder()
      .build_call(PrintfExtern::get(), args, "printf_call");
  }
}
```
</details

**Describe the solution you'd like**

I would like to find an alternative approach to retrieve the **`Context`** globally without using a closure, so that I can integrate it with my existing code structure. If there's a way to access the **`Context`** globally, even if it's non-thread safe and not suitable for production code, that would be acceptable.

<details>

<summary>Usage snippet example</summary>

```rust
    let basic_block = context.append_basic_block(abort_func, "entry");
    {
      builder.position_at_end(basic_block);

      let message_ptr = abort_func.get_param::<PointerValue>(0).unwrap();
      let exit_code = abort_func.get_param::<IntValue>(1).unwrap();

      PrintfExtern::call(&[message_ptr.into()]);
      ExitExtern::call_from_int(201);

      builder.build_unreachable();
    }
```

</details>

**Describe possible drawbacks to your solution**

Implementing a non-thread safe and globally accessible **`Context`** might hinder other components or users who rely on thread-safe behavior or have different requirements for managing the LLVM context. It is important to consider the potential impact on code organization and potential conflicts with other parts of the system.

**Describe alternatives you've considered**

One alternative I considered was using a **`singleton_manager`** for managing helpers and a global **`Context`**. However, this approach didn't work because the **`singleton_manager`** requires a static lifetime, which doesn't align with the dynamic nature of the Context.

**Additional context**

I have already tried using the **`get_global`** method of the **`Context`**, but the API requires passing a closure, which doesn't fit well with my code structure. I'm open to alternative approaches or suggestions for achieving the desired functionality.

**Comment by TheDan64** [comment]
Why can't you use a non global Context?

**Comment by Daniel-Boll** [comment]
I ultimately did refactor the code to keep providing context to everyone. At the time, I preferred my original design because the usage felt great that way, and then I discovered it was not possible, hence the refactor.

The problem is effectively solved. You can close it, although I still find the usage I was trying to achieve pretty great, this may be a useful feature, or I just don't think well in terms of coding this level of code 😅.

Anyways, thanks, man.
Best Regards, 
Daniel Boll. 🎴
