### ISSUE TITLE
Question: How to use LLVM `type`?

### ISSUE THREAD

**Issue by EricLBuehler** [TheDan64/inkwell#430]
Hello everbody,

When I create a custom struct type, I only get a `{ i132 }` at the location of use instead of other examples where a type `%t = type { i32 }` is defined and the type `%t` is used.

Is this a limitation with `llvm-sys` or `inkwell`? If not, how can I do this? 

Thank you for any help.

Example of what I want:
```
%union.Foo = type { i32 }
```

Instead of:
```
{ i32 }
```

**Comment by TheDan64** [comment]
Maybe it depends on the LLVM version you're using and the example you're looking at? The IR does change from version to version

**Comment by EricLBuehler** [comment]
I was looking at [this](https://mapping-high-level-constructs-to-llvm-ir.readthedocs.io/en/latest/basic-constructs/unions.html) site.

I would like to be able to use the type keyword because it makes the IR read better. Otherwise, as can be seen [here](https://github.com/EricLBuehler/Kestrel-Programming-Language/blob/master/a.ll), the IR becomes very cluttered with struct types.

When I run Clang on the following program, it uses the `type` keyword.

```
struct s {
    int i;
};

int main() {
    struct s x;
}
```

```
%struct.s = type { i32 }

; Function Attrs: noinline nounwind optnone uwtable
define dso_local i32 @main() #0 {
  %1 = alloca %struct.s, align 4
  ret i32 0
}
```

Is there a way in Inkwell to reproduce this? Perhaps some sort of type aliasing?

Thanks!

**Comment by TheDan64** [comment]
Not really sure tbh. Is your clang version identical to your llvm version?

**Comment by EricLBuehler** [comment]
Yes:
```
Ubuntu clang version 14.0.0-1ubuntu1
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```
After:
```
sudo apt install clang-14
sudo apt install clang
```
