### ISSUE TITLE
Question: What does `get_insert_block` returns.

### ISSUE THREAD

**Issue by vivekascoder** [TheDan64/inkwell#434]
What does it return?
https://thedan64.github.io/inkwell/inkwell/builder/struct.Builder.html#method.get_insert_block

Does it return the current basic block, builder is pointing at?

**Comment by EricLBuehler** [comment]
It gets the current block, or `None` in the case of Inkwell: https://llvm.org/doxygen/classllvm_1_1IRBuilderBase.html#a60a6d6c205f483fa96597a960f3c093b.
`GetInsertBlock` is called in the C++ API by https://llvm.org/doxygen/group__LLVMCCoreInstructionBuilder.html#gaf27b8e4dbb50f2dcde4f8c2a130b3356, which is the function `llvm-sys` calls.

**Comment by vivekascoder** [comment]
> It gets the current block, or `None` in the case of Inkwell: https://llvm.org/doxygen/classllvm_1_1IRBuilderBase.html#a60a6d6c205f483fa96597a960f3c093b. `GetInsertBlock` is called in the C++ API by https://llvm.org/doxygen/group__LLVMCCoreInstructionBuilder.html#gaf27b8e4dbb50f2dcde4f8c2a130b3356, which is the function `llvm-sys` calls.

thanks
