### ISSUE TITLE
Question: How can I get all defined structures?

### ISSUE THREAD

**Issue by Yinwhe** [TheDan64/inkwell#435]
Hi, I'm using inkwell to do some research on ir,  and I wanna know how to get all defined structures?

To get all functions I can use `get_functions`, but there is no similar function to get all structs. 
Maybe I didn't find the right function ?

**Comment by EricLBuehler** [comment]
As far as I know, Inkwell does not keep track of types. So, this means you need to keep track of the types you use. For example you can use a `HashMap` to associate the name and the `StructType`.

**Comment by Yinwhe** [comment]
> 

Oh I understand, thanks. In fact I'm using inkwell to analysis ir codes and find possible bugs, so maybe I won't parse all source code to get all these informations. Anyway, thanks.
