### ISSUE TITLE
Support llvm 17

### ISSUE THREAD

**Issue by Qwinci** [TheDan64/inkwell#444]
Add support for llvm 17, it removes the legacy optimization pipeline so this might be a decent amount of work to do, though I am not completely if all the PassManager stuff except the PassBuilderOptions and Module.run_passes() should just be disabled in llvm versions >= 17.

**Comment by gavrilikhin-d** [comment]
There is a [bug](https://github.com/llvm/llvm-project/issues/60432) in `MCJIT` in llvm 16 I've experienced today, that was fixed in newer version.
