### ISSUE TITLE
Interpreter?

### ISSUE THREAD

**Issue by alexreg** [TheDan64/inkwell#48]
Does this library support the LLVM interpreter, out of curiosity? http://llvm.org/doxygen/classllvm_1_1Interpreter.html

**Comment by TheDan64** [comment]
Yes, you can create an interpreter: https://thedan64.github.io/inkwell/inkwell/module/struct.Module.html#method.create_interpreter_execution_engine

**Comment by alexreg** [comment]
@TheDan64 Thanks. I saw this in fact (should have mentioned)... I was just wondering on the exact relation to the [`llvm::Interpreter` class](http://llvm.org/doxygen/classllvm_1_1Interpreter.html).

**Comment by TheDan64** [comment]
Apologies in advance if I'm not understanding your question!

The Inkwell `ExecutionEngine` created from that method is a wrapper on a pointer to the LLVM `Interpreter` class which, as I understand it, is a subclass of the LLVM `ExecutionEngine` base class.

This means that Inkwell's `ExecutionEngine` is roughly equivalent.. At the moment, it's too free as an Interpreter has methods that only the JIT `ExecutionEngine` should have access to (and vice versa), for example. This should be further restricted in v0.2.0 of inkwell. Nonetheless, an Inkwell EE should have all the methods that the class does (assuming there is a C API function equivalent for it and we haven't missed it)

Our EE docs (Interpreter, JIT, MCJIT, etc all combined ATM): https://thedan64.github.io/inkwell/inkwell/execution_engine/struct.ExecutionEngine.html
LLVM C API ExecutionEngine functions we have access to: https://bitbucket.org/tari/llvm-sys.rs/src/default/src/execution_engine.rs

Though it doesn't look like there are many interpreter specific methods in the C API so I'm not sure what good it is lol

**Comment by alexreg** [comment]
@TheDan64 Aha, thanks for clarifying. That makes sense to me. The `visit*` methods listed in my above link should be private, right? They look pretty low-level in any case, so they probably don't need to be exposed regardless.

Did you consider using direct C++ bindings incidentally, or did you deem that too painful? I know [`bindgen`](https://github.com/rust-lang-nursery/rust-bindgen) can do it for some libraries, for example, and with a bit of hand-tweaking...

**Comment by TheDan64** [comment]
Sure thing! According to the docs, it says they are public member functions, so I'm not sure why the C API doesn't expose them.

I decided to use llvm-sys (C API in rust) because it meant I could get this project up and running much faster instead of also having to maintain C++ bindings. That said, I'm not even sure if C++ bindings would work in every case... It does seem simpler to go through C bindings which are well known and have a stable ABI

**Comment by TheDan64** [comment]
C++ bindings might be worth considering in the future though... It just just sounds like a lot of work and I'd much rather work on Inkwell proper with what little spare time I have

**Comment by alexreg** [comment]
Yeah, C APIs are generally a lot easier to use than C++ ones from other languages, that's for sure. I'll leave it to you whether you want to migrate over to C++ bindings at some point, but I'm glad this seems to job for now. I'm not surely *precisely* what those methods do, but I don't imagine needing to call them directly to be honest.

**Comment by 6A** [comment]
Having C++ bindings does sound like a lot of work, and almost unnecessary, since (to my knowledge), most compilers that use LLVM only have bindings to the C API. If you do use this though, maybe having inline C++ declarations would help (using https://docs.rs/cpp)?

**Comment by alexreg** [comment]
@6A Interesting. Do existing Rust CPP bindings tend to use the `cpp` library... or just `rust-bindgen` / manually-written bindings?

**Comment by 6A** [comment]
@alexreg  I don't know any library that uses `cpp!`, but I thought I'd mention it anyway since it seems interesting for small use cases. Otherwise I think `bindgen` is more mature and widely used.

**Comment by TheDan64** [comment]
Closing as this thread has been inactive for the last few months. Feel free to reopen or open a new issue if you have any other questions, thanks!

**Comment by alexreg** [comment]
@TheDan64 Sorry, I should have closed it myself. I consider it resolved for now, yep. :-)
