### ISSUE TITLE
rename `build_bitcast` to `build_bit_cast`

### ISSUE THREAD

**Issue by Anton-4** [TheDan64/inkwell#485]
Hi,
Thanks for working on inkwell :heart:

Can `build_bitcast` be renamed to `build_bit_cast`? That would make it more consistent internally with `build_int_cast`, `build_float_cast`,... as well as with LLVM's `LLVMBuildBitCast`.

I can do the PR if desired.

**Comment by TheDan64** [comment]
This one is interesting, given that `bitcast` is a common term and others (ie `floatcast`) are not. That said, the more consistent naming seems like a good idea
