### ISSUE TITLE
tests do fail on os x

### ISSUE THREAD

**Issue by Licenser** [TheDan64/inkwell#49]
**Describe the Bug**

* `test_default_target_triple` fails to compile on OS X as it only has a case for linux .
* `test_target_data` fails on os x as the data layout differs.

**To Reproduce**
Run `cargo test` on os x

**Expected Behavior**
Tests pass

**LLVM Version (please complete the following information):**
(not related)
 - LLVM Version: 6.0
 - Inkwell Branch Used: llvm6-0

**Desktop (please complete the following information):**
 - OS: OS X

**Comment by TheDan64** [comment]
Thank you so much for reporting & fixing this! I wish I could better maintain OSX support but I don't have a mac unfortunately. OSX CI (#10) is definitely a high priority item after we get the upcoming initial release out, though.

**Comment by TheDan64** [comment]
@Licenser Can we close this issue now? Feel free to open it again if tests ever start to fail in OSX again :)

**Comment by Licenser** [comment]
oh yes sorry! of cause it can be closed.
