### ISSUE TITLE
Can I add an feature wich isn't in normal LLVM?

### ISSUE THREAD

**Issue by Toni-Graphics** [TheDan64/inkwell#500]
Hi, can I add a feature which isn't in normal LLVM?
Bye

**Comment by TheDan64** [comment]
Depends in what the request is

**Comment by Toni-Graphics** [comment]
I want to add an easy api for the builder.
As an example you can then do:

```
let mut ir: Vec<Box<dyn EasyIr> = vec![];
ir.push ( Return::new(5) );

EasyIr::gen(ir, &mut func, &mut context, &mut module); // Compile the the ir
```

It would be implemented like [here](https://github.com/Toni-Graphics/rllvm/blob/main/src/ir/mod.rs) and [here](https://github.com/Toni-Graphics/rllvm/blob/main/src/ir/compile.rs#L110)

Bye

**Comment by TheDan64** [comment]
This would probably be better suited in another library that wraps inkwell

**Comment by Toni-Graphics** [comment]
Ok
