### ISSUE TITLE
Cargo fails due to missing features

### ISSUE THREAD

**Issue by vitezprchal** [TheDan64/inkwell#504]
**Describe the Bug**
When attempting to build the project, the dependency resolution for the inkwell crate fails due to missing features.
```
error: failed to select a version for `inkwell`.
    ... required by package `example v0.1.0`
versions that meet the requirements `^0.4.0` (locked to 0.4.0) are: 0.4.0

the package `example` depends on `inkwell`, with features: `llvm18-0` but `inkwell` does not have these features.

```

**To Reproduce**
Cargo.toml
```
[dependencies]
inkwell={version="0.4.0",features=["llvm18-0"]}
```

**Expected Behavior**
Should resolve correctly without any feature-related errors, allowing the project to build successfully.

**LLVM Version (please complete the following information):**
 - LLVM Version: 18.1.17
 - Inkwell Branch Used: llvm18-0

**Desktop:**
 - OS: MacOS

**Comment by TheDan64** [comment]
LLVM 18 will be a part of 0.5.0 and hasn't been releases to crates.io yet
