### ISSUE TITLE
Build failing on Mac OS

### ISSUE THREAD

**Issue by spino17** [TheDan64/inkwell#509]
I am getting below error when running `cargo build`:
```
note: ld: library not found for -lzstd
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I have MacOS 14.5. I was working fine a day before an update installed.

**Comment by TheDan64** [comment]
You appear to be missing zstd on your system, so it cannot be linked in. Don't think this is an inkwell issue

**Comment by spino17** [comment]
ohh okay @TheDan64 . Will close here. Thanks!
