### ISSUE TITLE
String termination issue in write_to_file

### ISSUE THREAD

**Issue by tanin47** [TheDan64/inkwell#52]
The path within the method `write_to_file` doesn't seem to convert to a null-terminated string correctly

The method is here: https://github.com/TheDan64/inkwell/blob/master/src/targets.rs#L870

Please see the discussion here: https://www.reddit.com/r/rust/comments/98d8tb/new_to_rust_can_anyone_help_me_with_this_problem/e4fqji8/

@daboross seems to figure out how to solve it.

> Given that adding \0 fixes it, I think https://github.com/TheDan64/inkwell/blob/638306fdc79dd362ddf3cf474cbb794e6dcfb9c3/src/targets.rs#L875 is the line causing this.
> It is incorrectly sending a ptr to a rust &str to an FFI interface, where instead it should be turning it into a std::ffi::CString. CString would then guarantee there are no inner \0 bytes and that \0 is appended onto the end.

(I'm new to Rust (and C). So, I have a limited understanding of this issue)

**Comment by TheDan64** [comment]
Thanks for pointing this out as I missed the reddit thread! I will be sure to take a look at fixing it within the next few days

**Comment by TheDan64** [comment]
This should be fixed now - please re-open if the issue reappears.
