### ISSUE TITLE
llvm 18 not working on inkwell 0.4.0?

### ISSUE THREAD

**Issue by mornsoltice** [TheDan64/inkwell#520]
**Describe the Bug**
when i try to add inkwell to my project with 

```sh
inkwell = { version = "0.4.0", features = ["llvm18-0"] }
```

at first rust analyzer see this as an error but i just ignored it, and then when i install another package i got this warning

failed to select a version for `inkwell`.
    ... required by package `venti v0.1.0 (/home/soltice/Development/venti)`
versions that meet the requirements `^0.4.0` (locked to 0.4.0) are: 0.4.0

the package `venti` depends on `inkwell`, with features: `llvm18-0` but `inkwell` does not have these features.

failed to select a version for `inkwell` which could resolve this conflict

**To Reproduce**
i dont think this was my code problem

**Expected Behavior**

**LLVM Version (please complete the following information):**
 - LLVM Version: [18.1.8]
 - Inkwell Branch Used: inkwell = { version = "0.4.0", features = ["llvm18-0"] }

**Desktop (please complete the following information):**
 - OS: Archcraft

**Additional Context**

**Comment by TheDan64** [comment]
Inkwell 0.4.0 only has support for up to LLVM 17. We are almost ready to release a 0.5.0 with LLVM 18 here soon: https://github.com/TheDan64/inkwell/milestone/4

**Comment by mornsoltice** [comment]
oh, I thought it supports LLVM 18 because it says so in the readme:)

**Comment by TheDan64** [comment]
0.5.0 should now be available on crates.io
