### ISSUE TITLE
Implement safe API for operand bundles manipulation

### ISSUE THREAD

**Issue by airwoodix** [TheDan64/inkwell#523]
[Operand bundles](https://llvm.org/docs/LangRef.html#operand-bundles) can be attached to `call` and `invoke` instructions. Starting with LLVM18, `llvm-sys` exposes the [relevant bindings](https://docs.rs/llvm-sys/latest/llvm_sys/?search=operandbundle) for building instructions with attached operand bundles, as well as parsing operand bundles from those instructions.

I have a prototype implementation of a safe API here: https://github.com/TheDan64/inkwell/compare/master...airwoodix:inkwell:get-operand-bundles

Would you consider a PR upstreaming such changes?

**Comment by TheDan64** [comment]
Sure, would be happy to review a PR
