### ISSUE TITLE
Segmentation Fault (in possibly TargetMachine::write_to_file method)

### ISSUE THREAD

**Issue by Shadowmeth** [TheDan64/inkwell#545]
**Describe the Bug**
cargo run gives segmentation fault while giving 0 panics.
[code](https://hastebin.com/share/ixupobuxaj.rust)

**To Reproduce**
Add `inkwell = { version = "0.5.0", features = ["llvm18-0-prefer-static"] }` to cargo.toml and cargo run with the code provided above.

**Expected Behavior**
x86-64 assembly written to main.s

**LLVM Version:**
 - LLVM Version: 18.1.8
 - Inkwell version: 0.5.0

**Desktop:**
 - OS: Fedora 40

**Additional Context**
gdb output: 

![image](https://github.com/user-attachments/assets/67ee3b74-39a6-4c10-8975-96af6f3368c8)

cargo run output:

![image](https://github.com/user-attachments/assets/39f8a61b-8a93-4c34-95e9-5eea174504d1)

I assume this is either an internal LLVM issue or with Inkwell's write_to_file binding.

**Comment by PartyWumpus** [comment]
This is just llvm's fault, it often just segfaults on invalid LLVM IR instead of returning an error. In your case, the LLVM IR output is (via `println!("{}", module.to_string());`), it's invalid because it's missing a return instruction.
```llvm
define void @my_function() {
entry:
  %my_alloca = alloca i32, align 4
  store i32 42, ptr %my_alloca, align 4
}
```

**Comment by Shadowmeth** [comment]
Yeah you were right. Building a return statement makes it work fine. A bit weird that it just segfaults instead of giving proper error but oh well.
