### ISSUE TITLE
ir parser

### ISSUE THREAD

**Issue by Cr0a3** [TheDan64/inkwell#552]
Hello!

LLVM has a function for parsing their ir:[ https://github.com/llvm/llvm-project/blob/261a4026e8a367eda229879838709b92abaf445c/llvm/lib/IRReader/IRReader.cpp#L94](https://github.com/llvm/llvm-project/blob/main/llvm/lib/IRReader/IRReader.cpp#L94).

I couldn't find a ported ir parsing function in inkwell.

If there is one, please let me know, else i appriciate if this gets added.

Best,
Cr0a3

**Comment by TheDan64** [comment]
If you can find a corresponding function in the C interface, we can add it. See llvm-sys. The C++ interface is not accessible to us

**Comment by Cr0a3** [comment]
> If you can find a corresponding function in the C interface, we can add it. See llvm-sys. The C++ interface is not accessible to us


Hmm I found a function which parses IR from a memory buffer: https://docs.rs/llvm-sys/191.0.0/llvm_sys/ir_reader/fn.LLVMParseIRInContext.html

So yes, llvm-sys supports ir parsing, but only from buffers which I would also use and like

**Comment by Cr0a3** [comment]
gentle ping @TheDan64

**Comment by TheDan64** [comment]
We already support this as `Context::create_module_from_ir`

**Comment by Cr0a3** [comment]
> We already support this as `Context::create_module_from_ir`

Thank you!
