### ISSUE TITLE
Ask for help: How to declare local variables?

### ISSUE THREAD

**Issue by playXE** [TheDan64/inkwell#58]

**Comment by 71** [comment]
In LLVM, `alloca` is used at the start of the function to make some room for a variable. Then whenever you need to assign to your variable, you use `store`, and when you need to read that variable you use the `Value` returned by `build_alloca`.

For a concrete example, you can see [here](https://github.com/TheDan64/inkwell/blob/949634db3b3703f2c916661d3f1a8a454df5d2c8/examples/kaleidoscope/main.rs#L866-L878) for the part that allocates the memory at the start, and [here](https://github.com/TheDan64/inkwell/blob/949634db3b3703f2c916661d3f1a8a454df5d2c8/examples/kaleidoscope/main.rs#L892-L921) for the usage.

**Comment by playXE** [comment]
@71 thanks for the help!
