### ISSUE TITLE
`Module::print_to_file` creates the wrong file or panics.

### ISSUE THREAD

**Issue by caiopsouza** [TheDan64/inkwell#63]
**Describe the Bug**
`Module::print_to_file` creates the wrong file or panics.

**To Reproduce**
```rust
use inkwell::targets::Target;
use inkwell::targets::InitializationConfig;
use inkwell::context::Context;
use std::path::Path;

fn main() {
    Target::initialize_native(&InitializationConfig::default()).unwrap();
    let context = Context::create();
    let module = context.create_module("test");
    module.print_to_file(Path::new("test.ll")).unwrap();
}
```

**Expected Behavior**
Should create file `test.txt`, creates file `test.txtDid not find a valid Unicode path stringcalled ``Result::unwrap()`` on an ``Err`` value: ` instead.

**LLVM Version:**
 - LLVM Version: 6.0
 - Inkwell Branch Used: llvm6-0

**Rust version:**
- nightly-x86_64-unknown-linux-gnu
- rustc 1.33.0-nightly (b2b7a063a 2019-01-01)

**Desktop:**
 - OS: Linux Mint 19.1

**Additional Context**
Simple fix was calling `Path::new("test.ll\0")` instead.

Not sure if this actually fix the problem, or if it's just working for now.

**Comment by TheDan64** [comment]
This should be easy to fix, thanks for reporting!
