### ISSUE TITLE
Test case failed when we use a llvm which enable LLVM_ENABLE_ASSERTIONS option

### ISSUE THREAD

**Issue by longwusha** [TheDan64/inkwell#73]
**Describe the Bug**
Test case failed when we use a llvm which enable LLVM_ENABLE_ASSERTIONS option.

```shell
cargo test --all --no-default-features --features "llvm7-0" --verbose
       Fresh lazy_static v1.3.0
       Fresh ucd-util v0.1.3
       Fresh semver-parser v0.7.0
       Fresh unicode-xid v0.1.0
       Fresh utf8-ranges v1.0.2
       Fresh cc v1.0.34
       Fresh unicode-xid v0.0.4
       Fresh quote v0.3.15
       Fresh either v1.5.2
       Fresh thread_local v0.3.6
       Fresh regex-syntax v0.6.6
       Fresh semver v0.9.0
       Fresh synom v0.11.3
       Fresh memchr v2.2.0
       Fresh proc-macro2 v0.4.27
       Fresh libc v0.2.51
       Fresh syn v0.11.11
       Fresh aho-corasick v0.7.3
       Fresh quote v0.6.11
       Fresh enum-methods v0.0.8
       Fresh regex v1.1.5
       Fresh syn v0.15.30
       Fresh inkwell_internal_macros v0.1.0 (/work/project/inkwell/internal_macros)
       Fresh llvm-sys v70.1.0
       Fresh inkwell v0.1.0 (/work/project/inkwell)
    Finished dev [unoptimized + debuginfo] target(s) in 0.02s
     Running `/work/project/inkwell/target/debug/deps/inkwell-710be66657a29f6e`

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running `/work/project/inkwell/target/debug/deps/all-feb08d9805fc64a7`

running 91 tests
all-feb08d9805fc64a7: /work/tool/llvm/source/70/llvm-7.0.1/lib/IR/AttributeImpl.h:129: llvm::IntAttributeImpl::IntAttributeImpl(llvm::Attribute::AttrKind, uint64_t): Assertion `(Kind == Attribute::Alignment || Kind == Attribute::StackAlignment || Kind == Attribute::Dereferenceable || Kind == Attribute::DereferenceableOrNull || Kind == Attribute::AllocSize) && "Wrong kind for int attribute!"' failed.
all-feb08d9805fc64a7: /work/tool/llvm/source/70/llvm-7.0.1/lib/IR/Instructions.cpp:310: void llvm::CallInst::init(llvm::FunctionType*, llvm::Value*, llvm::ArrayRef<llvm::Value*>, llvm::ArrayRef<llvm::OperandBundleDefT<llvm::Value*> >, const llvm::Twine&): Assertion `(Args.size() == FTy->getNumParams() || (FTy->isVarArg() && Args.size() > FTy->getNumParams())) && "Calling a function with bad signature!"' failed.
error: process didn't exit successfully: `/work/project/inkwell/target/debug/deps/all-feb08d9805fc64a7` (signal: 6, SIGABRT: process abort signal)
```

**To Reproduce**
Use a llvm which enable LLVM_ENABLE_ASSERTIONS option to test our test case, it failed.

In the following content, I will show in detail how I manually compiled llvm.

**Expected Behavior**
1. Test case passed
2. As a safety wrapper, inkwell should be tested in a LLVM_ENABLE_ASSERTIONS enabled llvm environment.
This can help us to find many problems in advance, such as the number of incorrect parameters, the wrong parameter type, and the wrong range of values (especially when using integers instead of enum for some tests). These problems are encapsulated and often do not go wrong at compile time, but may cause a crash or panic when encountering some boundary conditions at runtime.

**LLVM Version (please complete the following information):**
 - LLVM Version: 7.0
 - Inkwell Branch Used: master

**Desktop (please complete the following information):**
 - OS: deepin linux 15.9.3

**Additional Context**
[LLVM compiler and install.txt](https://github.com/TheDan64/inkwell/files/3050303/LLVM.txt)

**Comment by nlewycky** [comment]
I can't find any documentation that LLVM intends to support custom/user-created attributes. Instead, this function is creates an AttributeRef based on a value <enum-attribute-kind, int-value> pair. I suggest the testcase use LLVMGetEnumAttributeKindForName("alignstack", strlen("alignstack")) for its KindID.

For safety, maybe it would make sense to replace this API with create_enum_attribute(name: &str) -> Result<Attribute, ()> (or Option) that checks with get_named_enum_kind_id before the call.
