### ISSUE TITLE
Misleading doc of StructType::get_name

### ISSUE THREAD

**Issue by OlegTheCat** [TheDan64/inkwell#77]
**Describe the Bug**
The docstring of `StructType::get_name` [states](https://github.com/TheDan64/inkwell/blob/db3d5c509ed3c318b4cc0274f678668912220a22/src/types/struct_type.rs#L229) that this function is used to determine whether struct type is opaque. As far as I understand this is not correct since non-opaque structs can have a name too.

**Expected Behavior**
Docstring should be something like `Gets the name of this StructType`.

**Comment by TheDan64** [comment]
Great catch!
