### ISSUE TITLE
Drop of two execution engines leads to segfault

### ISSUE THREAD

**Issue by OlegTheCat** [TheDan64/inkwell#78]
**Describe the Bug**
Drop of two execution engines made from the same module leads to a segfault.

**To Reproduce**
```
use inkwell::context::Context;
use inkwell::OptimizationLevel;

fn main() {
    let context = Context::create();
    let module = context.create_module("foo");
    let execution_engine = module.create_jit_execution_engine(OptimizationLevel::None).unwrap();
    let execution_engine = module.create_jit_execution_engine(OptimizationLevel::None).unwrap();
}
```
**Expected Behavior**
Segfault should not happen.

**LLVM Version (please complete the following information):**
 - LLVM Version: [e.g. 7.0.1]
 - Inkwell Branch Used: [e.g. llvm7-0]

**Desktop (please complete the following information):**
 - OS: OS X

**Comment by TheDan64** [comment]
Hmm I thought we covered this case in the module. Good catch!

**Comment by TheDan64** [comment]
Ohhh, I see. We check for this on the execution engine side; but not the module side. Should be easy enough to fix.
