### ISSUE TITLE
Support setting linkage for GlobalValues

### ISSUE THREAD

**Issue by hansihe** [TheDan64/inkwell#79]
LLVM supports setting linkage on `GlobalValue`s with `GlobalValue::setLinkage`. I want this to be possible through inkwell as well.

I have considered using the C API directly for doing this, but I thought I would open an issue here first.

If it is wanted, I can make a PR implementing it.

As an aside, thanks for the project! It has saved me a lot of time.

**Comment by TheDan64** [comment]
You're welcome, thanks for the kind words!

If the C api allows for it then we should absolutely support it. Please be sure to write a test or two!

**Comment by TheDan64** [comment]
Fixed by #81
