### ISSUE TITLE
Any way to query the predicate of an `ICmp` or `FCmp`?

### ISSUE THREAD

**Issue by cdisselkoen** [TheDan64/inkwell#86]
I was wondering if there is any way, given an `InstructionValue` with opcode `ICmp` or `FCmp`, to get the "predicate" of the instruction.  I.e., for the LLVM instruction `%3 = icmp slt i32 %0, %1`, I'm looking for how to get the `slt`.  My grepping through the `inkwell` codebase didn't turn up any uses of the LLVM C APIs `LLVMGetICmpPredicate()` or `LLVMGetFCmpPredicate()`.  If it's just that those bindings were missed, I'm happy to add.

**Comment by TheDan64** [comment]
It's likely it was just missed. Please feel free to submit a PR!
