### ISSUE TITLE
FunctionValue::add_attribute documentation issue

### ISSUE THREAD

**Issue by nepp2** [TheDan64/inkwell#97]
**Describe the Bug**
I believe the documentation here is mistaken:

https://thedan64.github.io/inkwell/inkwell/values/struct.FunctionValue.html#method.add_attribute

> Adds an Attribute to this FunctionValue if index is 0, otherwise to its parameter in the 1 - Nth position.

The 0 index adds an attribute to the function's return type. To add an attribute to the function itself, the index must be the max u32 value:

`let function_index : u32 = !0;`
(or some equivalent max_value function)

**To Reproduce**
`fv_val.add_attribute(0, context.create_string_attribute("my_attribute", ""));`

This puts the attribute by the return type, which is not what the documentation seems to imply:

`define "my_attribute" <ResultType> @<FunctionName> ([argument list])`

**Expected Behavior**

The documentation should clearly indicate how to index the three different types of attribute accepted by this function: parameter, return and function attributes.

**LLVM Version:**
 - LLVM Version: 7.0
 - Inkwell Branch Used: llvm7-0

**Desktop:**
 - OS: Windows 10

**Additional Context**

I lost a lot of time to this so I thought I should let you guys know that it can be confusing. The C++ library has a special index type instead of a plain u32, which means the correct usage is at least dicoverable. Here is a reference to the C++ source where the different attribute index types are defined:

https://llvm.org/doxygen/Attributes_8h_source.html#l00338

I would personally turn this into a Rust enum to make the usage obvious, although that would be a breaking change.

**Comment by TheDan64** [comment]
Thanks for pointing this out! Would you like to make this change?

I'm thinking about an enum like
```rust
enum AttributeLoc {
    Return,
    Param(u32),
    Function,
}
```
where `Return` -> 0, `Function` -> `u32::max_value()`, and `Param(X)` where `0 <= X <= u32::max_value() - 2`? (we can add +1 to it to normalize to what LLVM expects and assert `X <= u32::max_value() - 2`)
