### ISSUE TITLE
int_type.const_int_from_string radix can not be an arbitrary number

### ISSUE THREAD

**Issue by nlewycky** [TheDan64/inkwell#98]
**Describe the Bug**
LLVM will assert if the radix in LLVMConstIntOfStringAndSize (in LLVM C++ API, this is APInt c'tor) is not 2, 8, 10, 16 or 36.

Since that's a small finite list, we could use an enum to represent the valid values.

**To Reproduce**
The surprisingly thorough tests will already demonstrate the issue. tests/all/test_values.rs test_value_from_string() has this code:

```
    let i8_val = i8_type.const_int_from_string("0121", 3);

    assert_eq!(*i8_val.print_to_string(), *CString::new("i8 16").unwrap());
```

so simply executing the tests with an assert llvm build will fail:

```
$ cargo test --all --features=llvm7-0 -- test_value_from_string
   Finished dev [unoptimized + debuginfo] target(s) in 0.08s
     Running target/debug/deps/inkwell-3860d788201e18fe

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/all-4e4d32e48e3ec760

running 1 test
all-4e4d32e48e3ec760: /home/nicholas/llvm-7.0.1.src/lib/Support/APInt.cpp:1968: void llvm::APInt::fromString(unsigned int, llvm::StringRef, uint8_t): Assertion `(radix == 10 || radix == 8 || radix == 16 || radix == 2 || radix == 36) && "Radix should be 2, 8, 10, 16, or 36!"' failed.
error: process didn't exit successfully: `/home/nicholas/inkwell2/target/debug/deps/all-4e4d32e48e3ec760 test_value_from_string` (signal: 6, SIGABRT: process abort signal)
```

**Expected Behavior**
Not able to compile code which makes LLVM assert or UB outside unsafe block.

**LLVM Version (please complete the following information):**
 - LLVM Version: 7.0.1
 - Inkwell Branch Used: master

**Desktop (please complete the following information):**
 - OS: Debian unstable

**Additional Context**
As an alternative, we could have a "string that is known to be valid in radix X" type, which has runtime-checked construction from string, and an API that guarantees valid string manipulation (you may only assign 0-7 to a character in the string, you may subset it, you may concatenate it with another of its radix or a lesser radix, that kind of thing).

**Comment by TheDan64** [comment]
We should also assert that the string isn't empty and add a `# Panics` doc section to explain the assertion like so: https://doc.rust-lang.org/std/primitive.isize.html#panics
